function c(b){throw b;}var g=void 0,j=null;function aa(){return function(b){return b}}function k(b){return function(){return this[b]}}function l(b){return function(){return b}}var p,q=this;function ba(){}
function r(b){var a=typeof b;if(a=="object")if(b){if(b instanceof Array)return"array";else if(b instanceof Object)return a;var d=Object.prototype.toString.call(b);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof b.length=="number"&&typeof b.splice!="undefined"&&typeof b.propertyIsEnumerable!="undefined"&&!b.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof b.call!="undefined"&&typeof b.propertyIsEnumerable!="undefined"&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if(a=="function"&&typeof b.call=="undefined")return"object";return a}function t(b){return typeof b=="string"}function ca(b){return typeof b=="number"}var da="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),ea=0;function fa(b,a){function d(){}d.prototype=a.prototype;b.ba=a.prototype;b.prototype=new d};var ga={"\000":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},ha={"'":"\\'"};
function ia(b){var n;b=String(b);if(b.quote)return b.quote();else{for(var a=['"'],d=0;d<b.length;d++){var e=b.charAt(d),f=e.charCodeAt(0),h=a,i=d+1,m;if(!(m=ga[e])){if(!(f>31&&f<127))if(e in ha)e=ha[e];else if(e in ga)n=ha[e]=ga[e],e=n;else{f=e;m=e.charCodeAt(0);if(m>31&&m<127)f=e;else{if(m<256){if(f="\\x",m<16||m>256)f+="0"}else f="\\u",m<4096&&(f+="0");f+=m.toString(16).toUpperCase()}e=ha[e]=f}m=e}h[i]=m}a.push('"');return a.join("")}}
function ja(b,a){for(var d=0,e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=Math.max(e.length,f.length),i=0;d==0&&i<h;i++){var m=e[i]||"",n=f[i]||"",o=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var u=o.exec(m)||["","",""],G=s.exec(n)||["","",""];if(u[0].length==0&&G[0].length==0)break;d=ka(u[1].length==0?0:parseInt(u[1],10),G[1].length==0?0:parseInt(G[1],10))||ka(u[2].length==0,G[2].length==0)||ka(u[2],G[2])}while(d==
0)}return d}function ka(b,a){if(b<a)return-1;else if(b>a)return 1;return 0}function la(b){for(var a=0,d=0;d<b.length;++d)a=31*a+b.charCodeAt(d),a%=4294967296;return a};var ma,na,oa,pa,qa,ra=(qa="ScriptEngine"in q&&q.ScriptEngine()=="JScript")?q.ScriptEngineMajorVersion()+"."+q.ScriptEngineMinorVersion()+"."+q.ScriptEngineBuildVersion():"0";function v(b,a){this.f=qa?[]:"";b!=j&&this.append.apply(this,arguments)}qa?(v.prototype.P=0,v.prototype.append=function(b,a,d){a==j?this.f[this.P++]=b:(this.f.push.apply(this.f,arguments),this.P=this.f.length);return this}):v.prototype.append=function(b,a,d){this.f+=b;if(a!=j)for(var e=1;e<arguments.length;e++)this.f+=arguments[e];return this};v.prototype.clear=function(){qa?this.P=this.f.length=0:this.f=""};
v.prototype.toString=function(){if(qa){var b=this.f.join("");this.clear();b&&this.append(b);return b}else return this.f};var sa;function ta(){return q.navigator?q.navigator.userAgent:j}pa=oa=na=ma=!1;var ua;if(ua=ta()){var va=q.navigator;ma=ua.indexOf("Opera")==0;na=!ma&&ua.indexOf("MSIE")!=-1;oa=!ma&&ua.indexOf("WebKit")!=-1;pa=!ma&&!oa&&va.product=="Gecko"}var w=na,wa=pa,xa=oa,ya=q.navigator,za=(ya&&ya.platform||"").indexOf("Mac")!=-1,Aa;
a:{var Ba="",Ca;if(ma&&q.opera)var Da=q.opera.version,Ba=typeof Da=="function"?Da():Da;else if(wa?Ca=/rv\:([^\);]+)(\)|;)/:w?Ca=/MSIE\s+([^\);]+)(\)|;)/:xa&&(Ca=/WebKit\/(\S+)/),Ca)var Ea=Ca.exec(ta()),Ba=Ea?Ea[1]:"";if(w){var Fa,Ga=q.document;Fa=Ga?Ga.documentMode:g;if(Fa>parseFloat(Ba)){Aa=String(Fa);break a}}Aa=Ba}var Ha={};function Ia(b){return Ha[b]||(Ha[b]=ja(Aa,b)>=0)};!w||Ia("9");w&&Ia("8");function Ja(){}Ja.prototype.V=!1;Ja.prototype.L=function(){if(!this.V)this.V=!0,this.A()};Ja.prototype.A=function(){};function Ka(b,a){this.type=b;this.currentTarget=this.target=a}fa(Ka,Ja);Ka.prototype.A=function(){delete this.type;delete this.target;delete this.currentTarget};Ka.prototype.Q=!1;Ka.prototype.fa=!0;var La=new Function("a","return a");function Ma(b,a){b&&this.M(b,a)}fa(Ma,Ka);p=Ma.prototype;p.target=j;p.relatedTarget=j;p.offsetX=0;p.offsetY=0;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.button=0;p.keyCode=0;p.charCode=0;p.ctrlKey=!1;p.altKey=!1;p.shiftKey=!1;p.metaKey=!1;p.ea=!1;p.W=j;
p.M=function(b,a){var d=this.type=b.type;Ka.call(this,d);this.target=b.target||b.srcElement;this.currentTarget=a;var e=b.relatedTarget;if(e){if(wa)try{La(e.nodeName)}catch(f){e=j}}else if(d=="mouseover")e=b.fromElement;else if(d=="mouseout")e=b.toElement;this.relatedTarget=e;this.offsetX=b.offsetX!==g?b.offsetX:b.layerX;this.offsetY=b.offsetY!==g?b.offsetY:b.layerY;this.clientX=b.clientX!==g?b.clientX:b.pageX;this.clientY=b.clientY!==g?b.clientY:b.pageY;this.screenX=b.screenX||0;this.screenY=b.screenY||
0;this.button=b.button;this.keyCode=b.keyCode||0;this.charCode=b.charCode||(d=="keypress"?b.keyCode:0);this.ctrlKey=b.ctrlKey;this.altKey=b.altKey;this.shiftKey=b.shiftKey;this.metaKey=b.metaKey;this.ea=za?b.metaKey:b.ctrlKey;this.state=b.state;this.W=b;delete this.fa;delete this.Q};p.A=function(){Ma.ba.A.call(this);this.relatedTarget=this.currentTarget=this.target=this.W=j};var Na=Array.prototype,Oa=Na.indexOf?function(b,a,d){return Na.indexOf.call(b,a,d)}:function(b,a,d){d=d==j?0:d<0?Math.max(0,b.length+d):d;if(t(b))return!t(a)||a.length!=1?-1:b.indexOf(a,d);for(;d<b.length;d++)if(d in b&&b[d]===a)return d;return-1};function Pa(b,a){Na.sort.call(b,a||Qa)}function Ra(b,a){for(var d=0;d<b.length;d++)b[d]={index:d,value:b[d]};var e=a||Qa;Pa(b,function(b,a){return e(b.value,a.value)||b.index-a.index});for(d=0;d<b.length;d++)b[d]=b[d].value}
function Qa(b,a){return b>a?1:b<a?-1:0};function Sa(){}var Ta=0;p=Sa.prototype;p.key=0;p.D=!1;p.S=!1;p.M=function(b,a,d,e,f,h){r(b)=="function"?this.Y=!0:b&&b.handleEvent&&r(b.handleEvent)=="function"?this.Y=!1:c(Error("Invalid listener argument"));this.N=b;this.aa=a;this.src=d;this.type=e;this.capture=!!f;this.X=h;this.S=!1;this.key=++Ta;this.D=!1};p.handleEvent=function(b){return this.Y?this.N.call(this.X||this.src,b):this.N.handleEvent.call(this.N,b)};function x(b,a){this.Z=a;this.q=[];b>this.Z&&c(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<b;d++)this.q.push(this.i?this.i():{})}fa(x,Ja);x.prototype.i=j;x.prototype.U=j;x.prototype.getObject=function(){return this.q.length?this.q.pop():this.i?this.i():{}};function Ua(b,a){b.q.length<b.Z?b.q.push(a):Va(b,a)}function Va(b,a){if(b.U)b.U(a);else{var d=r(a);if(d=="object"||d=="array"||d=="function")if(r(a.L)=="function")a.L();else for(var e in a)delete a[e]}}
x.prototype.A=function(){x.ba.A.call(this);for(var b=this.q;b.length;)Va(this,b.pop());delete this.q};var Wa,Xa,Ya,Za,$a,ab,bb,cb,db,eb,fb;
(function(){function b(){return{n:0,C:0}}function a(){return[]}function d(){function b(a){return i.call(b.src,b.key,a)}return b}function e(){return new Sa}function f(){return new Ma}var h=qa&&!(ja(ra,"5.7")>=0),i;ab=function(b){i=b};if(h){Wa=function(){return m.getObject()};Xa=function(b){Ua(m,b)};Ya=function(){return n.getObject()};Za=function(b){Ua(n,b)};$a=function(){return o.getObject()};bb=function(){Ua(o,d())};cb=function(){return s.getObject()};db=function(b){Ua(s,b)};eb=function(){return u.getObject()};
fb=function(b){Ua(u,b)};var m=new x(0,600);m.i=b;var n=new x(0,600);n.i=a;var o=new x(0,600);o.i=d;var s=new x(0,600);s.i=e;var u=new x(0,600);u.i=f}else Wa=b,Xa=ba,Ya=a,Za=ba,$a=d,bb=ba,cb=e,db=ba,eb=f,fb=ba})();function gb(b,a,d){for(var e in b)a.call(d,b[e],e,b)}function hb(b){var a={},d;for(d in b)a[d]=b[d];return a};var ib={},y={},jb={},kb={};
function lb(b,a,d,e,f){if(a)if(r(a)=="array"){for(var h=0;h<a.length;h++)lb(b,a[h],d,e,f);return j}else{var e=!!e,i=y;a in i||(i[a]=Wa());i=i[a];e in i||(i[e]=Wa(),i.n++);var i=i[e],m=b[da]||(b[da]=++ea),n;i.C++;if(i[m]){n=i[m];for(h=0;h<n.length;h++)if(i=n[h],i.N==d&&i.X==f){if(i.D)break;return n[h].key}}else n=i[m]=Ya(),i.n++;h=$a();h.src=b;i=cb();i.M(d,h,b,a,e,f);d=i.key;h.key=d;n.push(i);ib[d]=i;jb[m]||(jb[m]=Ya());jb[m].push(i);b.addEventListener?(b==q||!b.da)&&b.addEventListener(a,h,e):b.attachEvent(a in
kb?kb[a]:kb[a]="on"+a,h);return d}else c(Error("Invalid event type"))}function mb(b,a,d,e){if(!e.O&&e.$){for(var f=0,h=0;f<e.length;f++)if(e[f].D){var i=e[f].aa;i.src=j;bb(i);db(e[f])}else f!=h&&(e[h]=e[f]),h++;e.length=h;e.$=!1;h==0&&(Za(e),delete y[b][a][d],y[b][a].n--,y[b][a].n==0&&(Xa(y[b][a]),delete y[b][a],y[b].n--),y[b].n==0&&(Xa(y[b]),delete y[b]))}}
function nb(b,a,d,e,f){var h=1,a=a[da]||(a[da]=++ea);if(b[a]){b.C--;b=b[a];b.O?b.O++:b.O=1;try{for(var i=b.length,m=0;m<i;m++){var n=b[m];n&&!n.D&&(h&=ob(n,f)!==!1)}}finally{b.O--,mb(d,e,a,b)}}return Boolean(h)}
function ob(b,a){var d=b.handleEvent(a);if(b.S){var e=b.key;if(ib[e]){var f=ib[e];if(!f.D){var h=f.src,i=f.type,m=f.aa,n=f.capture;h.removeEventListener?(h==q||!h.da)&&h.removeEventListener(i,m,n):h.detachEvent&&h.detachEvent(i in kb?kb[i]:kb[i]="on"+i,m);h=h[da]||(h[da]=++ea);m=y[i][n][h];if(jb[h]){var o=jb[h],s=Oa(o,f);s>=0&&Na.splice.call(o,s,1);o.length==0&&delete jb[h]}f.D=!0;m.$=!0;mb(i,n,h,m);delete ib[e]}}}return d}
ab(function(b,a){if(!ib[b])return!0;var d=ib[b],e=d.type,f=y;if(!(e in f))return!0;var f=f[e],h,i;sa===g&&(sa=w&&!q.addEventListener);if(sa){var m;if(!(m=a))a:{m="window.event".split(".");for(var n=q;h=m.shift();)if(n[h]!=j)n=n[h];else{m=j;break a}m=n}h=m;m=!0 in f;n=!1 in f;if(m){if(h.keyCode<0||h.returnValue!=g)return!0;a:{var o=!1;if(h.keyCode==0)try{h.keyCode=-1;break a}catch(s){o=!0}if(o||h.returnValue==g)h.returnValue=!0}}o=eb();o.M(h,this);h=!0;try{if(m){for(var u=Ya(),G=o.currentTarget;G;G=
G.parentNode)u.push(G);i=f[!0];i.C=i.n;for(var R=u.length-1;!o.Q&&R>=0&&i.C;R--)o.currentTarget=u[R],h&=nb(i,u[R],e,!0,o);if(n){i=f[!1];i.C=i.n;for(R=0;!o.Q&&R<u.length&&i.C;R++)o.currentTarget=u[R],h&=nb(i,u[R],e,!1,o)}}else h=ob(d,o)}finally{if(u)u.length=0,Za(u);o.L();fb(o)}return h}e=new Ma(a,this);try{h=ob(d,e)}finally{e.L()}return h});!w||Ia("9");!wa&&!w||w&&Ia("9")||wa&&Ia("1.9.1");w&&Ia("9");function pb(b){return t(b)?document.getElementById(b):b};function z(b){return b!=j&&b!==!1}function qb(b,a){var d=b[r.call(j,a)];return z(d)?d:(d=b._,z(d)?d:!1)}function rb(b){return Array.prototype.slice.call(b)}function sb(b){return Array.prototype.slice.call(arguments)}
var A=function tb(a){return z(z(a)?a.t:a)?a.t(a):function(){var d=tb[r.call(j,a)];return z(d)?d:tb._}().call(j,a)},vb=function ub(a,d){return z(z(a)?a.j:a)?a.j(a,d):function(){var d=ub[r.call(j,a)];return z(d)?d:ub._}().call(j,a,d)},B=function(){function b(b,a,h){return z(z(b)?b.K:b)?b.K(b,a,h):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a,h)}function a(b,a){return z(z(b)?b.K:b)?b.K(b,a):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a)}var d=j;return d=function(d,
f,h){switch(arguments.length){case 2:return a.call(this,d,f);case 3:return b.call(this,d,f,h)}c("Invalid arity: "+arguments.length)}}(),xb=function wb(a){return z(z(a)?a.v:a)?a.v(a):function(){var d=wb[r.call(j,a)];return z(d)?d:wb._}().call(j,a)},zb=function yb(a){return z(z(a)?a.w:a)?a.w(a):function(){var d=yb[r.call(j,a)];return z(d)?d:yb._}().call(j,a)},C=function(){function b(b,a,h){return z(z(b)?b.u:b)?b.u(b,a,h):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a,h)}function a(b,
a){return z(z(b)?b.u:b)?b.u(b,a):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a)}var d=j;return d=function(d,f,h){switch(arguments.length){case 2:return a.call(this,d,f);case 3:return b.call(this,d,f,h)}c("Invalid arity: "+arguments.length)}}(),Bb=function Ab(a,d,e){return z(z(a)?a.J:a)?a.J(a,d,e):function(){var d=Ab[r.call(j,a)];return z(d)?d:Ab._}().call(j,a,d,e)},Cb={},Db={},Eb={},Gb=function Fb(a){return z(z(a)?a.p:a)?a.b:function(){var d=Fb[r.call(j,a)];return z(d)?d:Fb._}().call(j,
a)},Ib=function Hb(a,d){return z(z(a)?a.m:a)?a.m(a,d):function(){var d=Hb[r.call(j,a)];return z(d)?d:Hb._}().call(j,a,d)},Jb=function(){function b(b,a,h){return z(z(b)?b.G:b)?b.G(b,a,h):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a,h)}function a(b,a){return z(z(b)?b.G:b)?b.G(b,a):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a)}var d=j;return d=function(d,f,h){switch(arguments.length){case 2:return a.call(this,d,f);case 3:return b.call(this,d,f,h)}c("Invalid arity: "+
arguments.length)}}(),Lb=function Kb(a,d){return z(z(a)?a.e:a)?a.e(a,d):function(){var d=Kb[r.call(j,a)];return z(d)?d:Kb._}().call(j,a,d)},Nb=function Mb(a){return z(z(a)?a.k:a)?a.k(a):function(){var d=Mb[r.call(j,a)];return z(d)?d:Mb._}().call(j,a)},Pb=function Ob(a){return z(z(a)?a.h:a)?a.h(a):function(){var d=Ob[r.call(j,a)];return z(d)?d:Ob._}().call(j,a)},Qb={},Rb={},Tb=function Sb(a,d){return z(z(a)?a.g:a)?a.g(a,d):function(){var d=Sb[r.call(j,a)];return z(d)?d:Sb._}().call(j,a,d)};
function Ub(b,a){return b===a}function D(b,a){return Lb.call(j,b,a)}function E(b){return Ub.call(j,b,j)}Lb["null"]=function(b,a){return E.call(j,a)};vb["null"]=function(b,a){return F.call(j,a)};xb["null"]=l(j);zb["null"]=function(){return F.call(j)};Ib["null"]=l(j);Cb["null"]=!0;B["null"]=function(){return function(b,a,d){switch(arguments.length){case 2:return j;case 3:return d}c("Invalid arity: "+arguments.length)}}();Eb["null"]=!0;Gb["null"]=l(j);
Jb["null"]=function(){return function(b,a,d){switch(arguments.length){case 2:return a.call(j);case 3:return d}c("Invalid arity: "+arguments.length)}}();Nb["null"]=l(0);A["null"]=l(0);Bb["null"]=function(b,a,d){return Vb.call(j,a,d)};C["null"]=function(){return function(b,a,d){switch(arguments.length){case 2:return j;case 3:return d}c("Invalid arity: "+arguments.length)}}();Date.prototype.e=function(b,a){return Ub.call(j,b.toString,a.toString)};Nb.number=aa();
Lb.number=function(b,a){return Ub.call(j,b,a)};function H(b){return b+1}function Wb(b,a){return b<a}
var I=function(){return function(b,a,d,e){switch(arguments.length){case 2:var f;a:if(z(D.call(j,0,A.call(j,b))))f=a.call(j);else for(var h=B.call(j,b,0),i=1;;)if(z(Wb.call(j,i,A.call(j,b))))h=a.call(j,h,B.call(j,b,i)),i=H.call(j,i);else{f=h;break a}return f;case 3:a:{f=d;for(i=0;;)if(z(Wb.call(j,i,A.call(j,b))))f=a.call(j,f,B.call(j,b,i)),i=H.call(j,i);else{h=f;break a}}return h;case 4:a:{f=d;for(h=e;;)if(z(Wb.call(j,h,A.call(j,b))))f=a.call(j,f,B.call(j,b,h)),h=H.call(j,h);else{i=f;break a}}return i}c("Invalid arity: "+
arguments.length)}}();function Xb(b,a){this.s=b;this.B=a}p=Xb.prototype;p.G=function(){return function(b,a,d){switch(arguments.length){case 2:return I.call(j,this.s,a,this.s[this.B],H.call(j,this.B));case 3:return I.call(j,this.s,a,d,this.B)}c("Invalid arity: "+arguments.length)}}();p.e=function(b,a){return Yb.call(j,b,a)};p.z=!0;p.v=function(){return this.s[this.B]};p.w=function(){return z(Wb.call(j,H.call(j,this.B),A.call(j,this.s)))?new Xb(this.s,H.call(j,this.B)):F.call(j)};p.h=aa();
function Zb(b,a){return z(D.call(j,0,A.call(j,b)))?j:new Xb(b,a)}function J(b,a){return Zb.call(j,b,a)}Jb.array=function(){return function(b,a,d){switch(arguments.length){case 2:return I.call(j,b,a);case 3:return I.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();C.array=function(){return function(b,a,d){switch(arguments.length){case 2:return b[a];case 3:return B.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();
B.array=function(){return function(b,a,d){switch(arguments.length){case 2:return z(Wb.call(j,a,b.length))?b[a]:j;case 3:return z(Wb.call(j,a,b.length))?b[a]:d}c("Invalid arity: "+arguments.length)}}();A.array=function(b){return b.length};Pb.array=function(b){return J.call(j,b,0)};function K(b){return z(b)?Pb.call(j,b):j}function L(b){b=K.call(j,b);return z(b)?xb.call(j,b):j}function M(b){return zb.call(j,K.call(j,b))}function N(b){return z(b)?K.call(j,M.call(j,b)):j}
function $b(b){return L.call(j,N.call(j,b))}function ac(b){return N.call(j,N.call(j,b))}A._=function(b){for(var b=K.call(j,b),a=0;;)if(z(b))b=N.call(j,b),a=H.call(j,a);else return a};Lb._=function(b,a){return Ub.call(j,b,a)};function bc(b){return z(b)?!1:!0}
var cc=function(){function b(b,e,f){for(var h=J(Array.prototype.slice.call(arguments,2),0);;)if(z(h))var i=a.call(j,b,e),m=L.call(j,h),h=N.call(j,h),b=i,e=m;else return a.call(j,b,e)}var a=j,a=function(a,e,f){switch(arguments.length){case 2:return vb.call(j,a,e);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}();function dc(b){return A.call(j,b)}
var ec=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,b,a);case 3:return C.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}(),fc=function(){function b(b,e,f,h){for(var i=J(Array.prototype.slice.call(arguments,3),0);;){var m=a.call(j,b,e,f);if(z(i))var n=L.call(j,i),o=$b.call(j,i),i=ac.call(j,i),b=m,e=n,f=o;else return m}}var a=j,a=function(a,e,f,h){switch(arguments.length){case 3:return Bb.call(j,a,e,f);default:return b.apply(this,arguments)}c("Invalid arity: "+
arguments.length)};a.c=3;a.a=function(a){var e=L(a),f=L(N(a)),h=L(N(N(a))),a=M(N(N(a)));return b.call(j,e,f,h,a)};return a}();function gc(b,a){return Ib.call(j,b,a)}function hc(b){return Gb.call(j,b)}function ic(b){return Nb.call(j,b)}function jc(b){return z(z(b)?b.z:b)?!0:qb.call(j,Qb,b)}function kc(b){return z(E.call(j,b))?!1:z(z(b)?b.T:b)?!0:qb.call(j,Cb,b)}function lc(b){return z(z(b)?b.ca:b)?!0:qb.call(j,Db,b)}
function mc(b){var a=sb.call(j);gb.call(j,b,function(b,e){return a.push(e)});return a}function nc(b){return g===b}function oc(b){return z(b)?!0:!1}function pc(b){var a=t.call(j,b);return z(a)?bc.call(j,function(){var a=D.call(j,b.charAt(0),"\ufdd0");return z(a)?a:D.call(j,b.charAt(0),"\ufdd1")}()):a}function qc(b){var a=t.call(j,b);return z(a)?D.call(j,b.charAt(0),"\ufdd0"):a}function rc(b){var a=t.call(j,b);return z(a)?D.call(j,b.charAt(0),"\ufdd1"):a}function sc(b){return ca.call(j,b)}
function tc(b,a){return Qa.call(j,b,a)}function uc(b){return z(D.call(j,b,tc))?tc:function(a,d){var e=b.call(j,a,d);return z(sc.call(j,e))?e:z(e)?-1:z(b.call(j,d,a))?1:0}}
var wc=function(){var b=j;return b=function(a,d){switch(arguments.length){case 1:return b.call(j,tc,a);case 2:var e;z(K.call(j,d))?(e=O.call(j,d),Ra.call(j,e,uc.call(j,a)),e=K.call(j,e)):e=vc;return e}c("Invalid arity: "+arguments.length)}}(),P=function(){return function(b,a,d){switch(arguments.length){case 2:return Jb.call(j,a,b);case 3:return Jb.call(j,d,b,a)}c("Invalid arity: "+arguments.length)}}(),xc=function(){return function(b,a,d){switch(arguments.length){case 2:var e=K.call(j,a);return z(e)?
P.call(j,b,L.call(j,e),N.call(j,e)):b.call(j);case 3:a:for(var f=a,h=K.call(j,d);;)if(z(h))f=b.call(j,f,L.call(j,h)),h=N.call(j,h);else{e=f;break a}return e}c("Invalid arity: "+arguments.length)}}();Jb._=function(){return function(b,a,d){switch(arguments.length){case 2:return xc.call(j,a,b);case 3:return xc.call(j,a,d,b)}c("Invalid arity: "+arguments.length)}}();
var yc=function(){function b(b,e,f){var h=J(Array.prototype.slice.call(arguments,2),0);return P.call(j,a,a.call(j,b,e),h)}var a=j,a=function(a,e,f){switch(arguments.length){case 0:return 0;case 1:return a;case 2:return a+e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),zc=function(){function b(b,e,f){var h=J(Array.prototype.slice.call(arguments,2),0);return P.call(j,a,a.call(j,b,
e),h)}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return-a;case 2:return a-e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),Ac=function(){function b(b,e,f){var h=J(Array.prototype.slice.call(arguments,2),0);return P.call(j,a,a.call(j,b,e),h)}var a=j,a=function(a,e,f){switch(arguments.length){case 0:return 1;case 1:return a;case 2:return a*e;default:return b.apply(this,
arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),Q=function(){function b(b,e,f){for(var h=J(Array.prototype.slice.call(arguments,2),0);;)if(z(a.call(j,b,e)))if(z(N.call(j,h)))var i=e,m=L.call(j,h),h=N.call(j,h),b=i,e=m;else return a.call(j,e,L.call(j,h));else return!1}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a<e;default:return b.apply(this,arguments)}c("Invalid arity: "+
arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),Bc=function(){function b(b,e,f){for(var h=J(Array.prototype.slice.call(arguments,2),0);;)if(z(a.call(j,b,e)))if(z(N.call(j,h)))var i=e,m=L.call(j,h),h=N.call(j,h),b=i,e=m;else return a.call(j,e,L.call(j,h));else return!1}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a<=e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=
function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),Cc=function(){function b(b,e,f){for(var h=J(Array.prototype.slice.call(arguments,2),0);;)if(z(a.call(j,b,e)))if(z(N.call(j,h)))var i=e,m=L.call(j,h),h=N.call(j,h),b=i,e=m;else return a.call(j,e,L.call(j,h));else return!1}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a>e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),
a=M(N(a));return b.call(j,e,f,a)};return a}(),Dc=function(){function b(b,e,f){for(var h=J(Array.prototype.slice.call(arguments,2),0);;)if(z(a.call(j,b,e)))if(z(N.call(j,h)))var i=e,m=L.call(j,h),h=N.call(j,h),b=i,e=m;else return a.call(j,e,L.call(j,h));else return!1}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a>=e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,
f,a)};return a}();function Ec(b){return zc.call(j,b,1)}function Fc(b,a){return b^a}function Gc(b,a){return b<<a}function Hc(b,a){return b>>a}function Ic(b){return Q.call(j,0,b)}function Jc(b,a){for(var d=a,e=K.call(j,b);;)if(z(function(){var b=e;return z(b)?Ic.call(j,d):b}()))var f=Ec.call(j,d),h=N.call(j,e),d=f,e=h;else return e}
B._=function(){return function(b,a,d){switch(arguments.length){case 2:var e;var f=Jc.call(j,b,a);z(f)?e=L.call(j,f):c("Index out of bounds");return e;case 3:return e=Jc.call(j,b,a),z(e)?L.call(j,e):d}c("Invalid arity: "+arguments.length)}}();
var S=function(){function b(b,e){var f=J(Array.prototype.slice.call(arguments,1),0);return function(b,d){for(;;)if(z(d))var e=b.append(a.call(j,L.call(j,d))),f=N.call(j,d),b=e,d=f;else return a.call(j,b)}.call(j,new v(a.call(j,b)),f)}var a=j,a=function(a,e){switch(arguments.length){case 0:return"";case 1:return z(E.call(j,a))?"":a.toString();default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=1;a.a=function(a){var e=L(a),a=M(a);return b.call(j,e,a)};return a}(),Kc=function(){return function(b,
a,d){switch(arguments.length){case 2:return b.substring(a);case 3:return b.substring(a,d)}c("Invalid arity: "+arguments.length)}}();function Yb(b,a){return oc.call(j,z(jc.call(j,a))?function(){for(var d=K.call(j,b),e=K.call(j,a);;)if(z(E.call(j,d)))return E.call(j,e);else if(z(E.call(j,e)))return!1;else if(z(D.call(j,L.call(j,d),L.call(j,e))))d=N.call(j,d),e=N.call(j,e);else return z("\ufdd0'else")?!1:j}():j)}
function Lc(b,a){return Fc.call(j,b,yc.call(j,a,2654435769,Gc.call(j,b,6),Hc.call(j,b,2)))}function Mc(b){return P.call(j,function(b,d){return Lc.call(j,b,ic.call(j,d))},ic.call(j,L.call(j,b)),N.call(j,b))}function Nc(b,a,d,e){this.b=b;this.H=a;this.F=d;this.count=e}p=Nc.prototype;p.e=function(b,a){return Yb.call(j,b,a)};p.j=function(b,a){return new Nc(this.b,a,b,H.call(j,this.count))};p.v=k("H");p.w=k("F");p.h=aa();p.m=function(b,a){return new Nc(a,this.H,this.F,this.count)};p.o=!0;p.p=k("b");
p.k=function(b){return Mc.call(j,b)};p.t=k("count");p.z=!0;function Oc(b){this.b=b}p=Oc.prototype;p.e=function(b,a){return Yb.call(j,b,a)};p.j=function(b,a){return new Nc(this.b,a,j,1)};p.v=l(j);p.w=l(j);p.h=l(j);p.m=function(b,a){return new Oc(a)};p.o=!0;p.p=k("b");p.k=function(b){return Mc.call(j,b)};p.t=l(0);p.z=!0;var vc=new Oc(j);function Pc(b){return P.call(j,cc,vc,b)}function F(b){var a=J(Array.prototype.slice.call(arguments,0),0);return P.call(j,cc,vc,Pc.call(j,a))}
function Qc(b,a,d){this.b=b;this.H=a;this.F=d}p=Qc.prototype;p.h=aa();p.k=function(b){return Mc.call(j,b)};p.e=function(b,a){return Yb.call(j,b,a)};p.z=!0;p.j=function(b,a){return new Qc(j,a,b)};p.v=k("H");p.w=function(){return z(E.call(j,this.F))?vc:this.F};p.o=!0;p.p=k("b");p.m=function(b,a){return new Qc(a,this.H,this.F)};function T(b,a){return new Qc(j,b,a)}
Jb.string=function(){return function(b,a,d){switch(arguments.length){case 2:return I.call(j,b,a);case 3:return I.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();C.string=function(){return function(b,a,d){switch(arguments.length){case 2:return B.call(j,b,a);case 3:return B.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();
B.string=function(){return function(b,a,d){switch(arguments.length){case 2:return z(Q.call(j,a,A.call(j,b)))?b.charAt(a):j;case 3:return z(Q.call(j,a,A.call(j,b)))?b.charAt(a):d}c("Invalid arity: "+arguments.length)}}();A.string=function(b){return b.length};Pb.string=function(b){return Zb.call(j,b,0)};Nb.string=function(b){return la.call(j,b)};
String.prototype.call=function(){return function(b,a,d){switch(arguments.length){case 2:return ec.call(j,a,this.toString());case 3:return ec.call(j,a,this.toString(),d)}c("Invalid arity: "+arguments.length)}}();function Rc(b){var a=b.x;return z(b.R)?a:(b.x=a.call(j),b.R=!0,b.x)}function U(b,a,d){this.b=b;this.R=a;this.x=d}p=U.prototype;p.h=function(b){return K.call(j,Rc.call(j,b))};p.k=function(b){return Mc.call(j,b)};p.e=function(b,a){return Yb.call(j,b,a)};p.z=!0;
p.j=function(b,a){return T.call(j,a,b)};p.v=function(b){return L.call(j,Rc.call(j,b))};p.w=function(b){return M.call(j,Rc.call(j,b))};p.o=!0;p.p=k("b");p.m=function(b,a){return new U(a,this.R,this.x)};function O(b){for(var a=sb.call(j);;)if(z(K.call(j,b)))a.push(L.call(j,b)),b=N.call(j,b);else return a}function Sc(b,a){for(var d=b,e=a,f=0;;)if(z(function(){var b=Ic.call(j,e);return z(b)?K.call(j,d):b}()))var h=N.call(j,d),i=Ec.call(j,e),f=H.call(j,f),d=h,e=i;else return f}
var Uc=function Tc(a){return z(E.call(j,a))?j:z(E.call(j,N.call(j,a)))?K.call(j,L.call(j,a)):z("\ufdd0'else")?T.call(j,L.call(j,a),Tc.call(j,N.call(j,a))):j},Vc=function(){function b(b,a,d){var e=J(Array.prototype.slice.call(arguments,2),0);return function s(b,a){return new U(j,!1,function(){var d=K.call(j,b);return z(d)?T.call(j,L.call(j,d),s.call(j,M.call(j,d),a)):z(a)?s.call(j,L.call(j,a),N.call(j,a)):j})}.call(j,f.call(j,b,a),e)}function a(b,a){return new U(j,!1,function(){var d=K.call(j,b);return z(d)?
T.call(j,L.call(j,d),f.call(j,M.call(j,d),a)):a})}function d(b){return new U(j,!1,function(){return b})}function e(){return new U(j,!1,l(j))}var f=j,f=function(h,f,m){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,h);case 2:return a.call(this,h,f);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};f.c=2;f.a=function(a){var d=L(a),e=L(N(a)),a=M(N(a));return b.call(j,d,e,a)};return f}(),Wc=function(){function b(b,a,f,h,i){var m=J(Array.prototype.slice.call(arguments,
4),0);return T.call(j,b,T.call(j,a,T.call(j,f,T.call(j,h,Uc.call(j,m)))))}var a=j,a=function(a,e,f,h,i){switch(arguments.length){case 1:return K.call(j,a);case 2:return T.call(j,a,e);case 3:return T.call(j,a,T.call(j,e,f));case 4:return T.call(j,a,T.call(j,e,T.call(j,f,h)));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=4;a.a=function(a){var e=L(a),f=L(N(a)),h=L(N(N(a))),i=L(N(N(N(a)))),a=M(N(N(N(a))));return b.call(j,e,f,h,i,a)};return a}(),Xc=function(){function b(a,
b,f,h,i,m){var n=J(Array.prototype.slice.call(arguments,5),0),n=T.call(j,b,T.call(j,f,T.call(j,h,T.call(j,i,Uc.call(j,n))))),o=a.c;return z(a.a)?z(Bc.call(j,Sc.call(j,n,o),o))?a.apply(a,O.call(j,n)):a.a(n):a.apply(a,O.call(j,n))}var a=j,a=function(a,e,f,h,i,m){switch(arguments.length){case 2:var n=a,o=e,s=n.c;return z(n.a)?z(Bc.call(j,Sc.call(j,o,s),s))?n.apply(n,O.call(j,o)):n.a(o):n.apply(n,O.call(j,o));case 3:return n=a,o=Wc.call(j,e,f),s=n.c,z(n.a)?z(Bc.call(j,Sc.call(j,o,s),s))?n.apply(n,O.call(j,
o)):n.a(o):n.apply(n,O.call(j,o));case 4:return n=a,o=Wc.call(j,e,f,h),s=n.c,z(n.a)?z(Bc.call(j,Sc.call(j,o,s),s))?n.apply(n,O.call(j,o)):n.a(o):n.apply(n,O.call(j,o));case 5:return n=a,o=Wc.call(j,e,f,h,i),s=n.c,z(n.a)?z(Bc.call(j,Sc.call(j,o,s),s))?n.apply(n,O.call(j,o)):n.a(o):n.apply(n,O.call(j,o));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=5;a.a=function(a){var e=L(a),f=L(N(a)),h=L(N(N(a))),i=L(N(N(N(a)))),m=L(N(N(N(N(a))))),a=M(N(N(N(N(a)))));return b.call(j,
e,f,h,i,m,a)};return a}();function Yc(b,a){for(;;)if(z(E.call(j,K.call(j,a))))return!0;else if(z(b.call(j,L.call(j,a))))var d=b,e=N.call(j,a),b=d,a=e;else return z("\ufdd0'else")?!1:j}function Zc(b){return b}
var V=function(){function b(a,b,d,e,o){var s=J(Array.prototype.slice.call(arguments,4),0);return f.call(j,function(b){return Xc.call(j,a,b)},function G(a){return new U(j,!1,function(){var b=f.call(j,K,a);return z(Yc.call(j,Zc,b))?T.call(j,f.call(j,L,b),G.call(j,f.call(j,M,b))):j})}.call(j,cc.call(j,s,e,d,b)))}function a(a,b,d,e){return new U(j,!1,function(){var o=K.call(j,b),s=K.call(j,d),u=K.call(j,e);return z(z(o)?z(s)?u:s:o)?T.call(j,a.call(j,L.call(j,o),L.call(j,s),L.call(j,u)),f.call(j,a,M.call(j,
o),M.call(j,s),M.call(j,u))):j})}function d(a,b,d){return new U(j,!1,function(){var e=K.call(j,b),o=K.call(j,d);return z(z(e)?o:e)?T.call(j,a.call(j,L.call(j,e),L.call(j,o)),f.call(j,a,M.call(j,e),M.call(j,o))):j})}function e(a,b){return new U(j,!1,function(){var d=K.call(j,b);return z(d)?T.call(j,a.call(j,L.call(j,d)),f.call(j,a,M.call(j,d))):j})}var f=j,f=function(f,i,m,n,o){switch(arguments.length){case 2:return e.call(this,f,i);case 3:return d.call(this,f,i,m);case 4:return a.call(this,f,i,m,
n);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};f.c=4;f.a=function(a){var d=L(a),e=L(N(a)),f=L(N(N(a))),o=L(N(N(N(a)))),a=M(N(N(N(a))));return b.call(j,d,e,f,o,a)};return f}(),ad=function $c(a,d){return new U(j,!1,function(){if(z(Ic.call(j,a))){var e=K.call(j,d);return z(e)?T.call(j,L.call(j,e),$c.call(j,Ec.call(j,a),M.call(j,e))):j}else return j})};
function bd(b,a){function d(a,b){for(;;){var d=K.call(j,b);if(z(function(){var b=Ic.call(j,a);return z(b)?d:b}()))var i=Ec.call(j,a),m=M.call(j,d),a=i,b=m;else return d}}return new U(j,!1,function(){return d.call(j,b,a)})}
var cd=function(){function b(b){return new U(j,!1,function(){return T.call(j,b,a.call(j,b))})}var a=j;return a=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return ad.call(j,d,a.call(j,e))}c("Invalid arity: "+arguments.length)}}(),dd=function(){function b(a,b,h){var i=J(Array.prototype.slice.call(arguments,2),0);return new U(j,!1,function(){var h=V.call(j,K,cc.call(j,i,b,a));return z(Yc.call(j,Zc,h))?Vc.call(j,V.call(j,L,h),Xc.call(j,d,V.call(j,M,h))):j})}function a(a,
b){return new U(j,!1,function(){var h=K.call(j,a),i=K.call(j,b);return z(z(h)?i:h)?T.call(j,L.call(j,h),T.call(j,L.call(j,i),d.call(j,M.call(j,h),M.call(j,i)))):j})}var d=j,d=function(d,f,h){switch(arguments.length){case 2:return a.call(this,d,f);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};d.c=2;d.a=function(a){var d=L(a),h=L(N(a)),a=M(N(a));return b.call(j,d,h,a)};return d}();function ed(b,a){return bd.call(j,1,dd.call(j,cd.call(j,b),a))}
function fd(b){return function d(b,f){return new U(j,!1,function(){var h=K.call(j,b);return z(h)?T.call(j,L.call(j,h),d.call(j,M.call(j,h),f)):z(K.call(j,f))?d.call(j,L.call(j,f),M.call(j,f)):j})}.call(j,j,b)}
var gd=function(){function b(a,b,f){var h=J(Array.prototype.slice.call(arguments,2),0);return fd.call(j,Xc.call(j,V,a,b,h))}var a=j,a=function(a,e,f){switch(arguments.length){case 2:return fd.call(j,V.call(j,a,e));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),id=function hd(a,d){return new U(j,!1,function(){var e=K.call(j,d);if(z(e)){var f=L.call(j,e),e=M.call(j,e);return z(a.call(j,
f))?T.call(j,f,hd.call(j,a,e)):hd.call(j,a,e)}else return j})};function jd(b,a){return P.call(j,vb,b,a)}
var kd=function(){function b(a,b,h,i){return new U(j,!1,function(){var m=K.call(j,i);if(z(m)){var n=ad.call(j,a,m);return z(D.call(j,a,dc.call(j,n)))?T.call(j,n,d.call(j,a,b,h,bd.call(j,b,m))):F.call(j,ad.call(j,a,Vc.call(j,n,h)))}else return j})}function a(a,b,h){return new U(j,!1,function(){var i=K.call(j,h);if(z(i)){var m=ad.call(j,a,i);return z(D.call(j,a,dc.call(j,m)))?T.call(j,m,d.call(j,a,b,bd.call(j,b,i))):j}else return j})}var d=j;return d=function(e,f,h,i){switch(arguments.length){case 2:return d.call(j,
e,e,f);case 3:return a.call(this,e,f,h);case 4:return b.call(this,e,f,h,i)}c("Invalid arity: "+arguments.length)}}();function W(b,a){this.b=b;this.d=a}p=W.prototype;p.e=function(b,a){return Yb.call(j,b,a)};p.j=function(b,a){var d=rb.call(j,this.d);d.push(a);return new W(this.b,d)};p.h=function(){var b=this;return z(Cc.call(j,b.d.length,0))?function d(e){return new U(j,!1,function(){return z(Q.call(j,e,b.d.length))?T.call(j,b.d[e],d.call(j,H.call(j,e))):j})}.call(j,0):j};p.ca=!0;
p.m=function(b,a){return new W(a,this.d)};p.K=function(){function b(a,b,f){var h=this;return z(function(){var a=Bc.call(j,0,b);return z(a)?Q.call(j,b,h.d.length):a}())?h.d[b]:f}function a(a,b){var f=this;return z(function(){var a=Bc.call(j,0,b);return z(a)?Q.call(j,b,f.d.length):a}())?f.d[b]:j}return function(d,e,f){switch(arguments.length){case 2:return a.call(this,0,e);case 3:return b.call(this,0,e,f)}c("Invalid arity: "+arguments.length)}}();p.o=!0;p.p=k("b");
p.G=function(){return function(b,a,d){switch(arguments.length){case 2:return I.call(j,this.d,a);case 3:return I.call(j,this.d,a,d)}c("Invalid arity: "+arguments.length)}}();p.k=function(b){return Mc.call(j,b)};p.t=function(){return this.d.length};p.z=!0;p.J=function(b,a,d){b=rb.call(j,this.d);b[a]=d;return new W(this.b,b)};p.u=function(){return function(b,a,d){switch(arguments.length){case 2:return B.call(j,b,a,j);case 3:return B.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();
var ld=new W(j,sb.call(j));function md(b){return new W(j,b)}W.prototype.call=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,this,a);case 3:return C.call(j,this,a,d)}c("Invalid arity: "+arguments.length)}}();function nd(b){return P.call(j,cc,ld,b)}function od(b){var a=J(Array.prototype.slice.call(arguments,0),0);return nd.call(j,a)}function pd(){}pd.prototype.e=l(!1);var qd=new pd;
function rd(b,a){return oc.call(j,z(kc.call(j,a))?z(D.call(j,dc.call(j,b),dc.call(j,a)))?Yc.call(j,Zc,V.call(j,function(b){return D.call(j,ec.call(j,a,L.call(j,b),qd),$b.call(j,b))},b)):j:j)}function sd(b,a,d){for(var e=d.length,f=0;;)if(z(Q.call(j,f,e)))if(z(D.call(j,a,d[f])))return f;else f=yc.call(j,f,b);else return j}
var td=function(){function b(a,b,f,h){return z(function(){var f=t.call(j,a);return z(f)?b.hasOwnProperty(a):f}())?f:h}var a=j;return a=function(d,e,f,h){switch(arguments.length){case 2:return a.call(j,d,e,!0,!1);case 4:return b.call(this,d,e,f,h)}c("Invalid arity: "+arguments.length)}}();function X(b,a,d){this.b=b;this.keys=a;this.I=d}p=X.prototype;p.e=function(b,a){return rd.call(j,b,a)};p.j=function(b,a){return z(lc.call(j,a))?Bb.call(j,b,B.call(j,a,0),B.call(j,a,1)):P.call(j,vb,b,a)};
p.h=function(){var b=this;return z(Ic.call(j,b.keys.length))?V.call(j,function(a){return od.call(j,a,b.I[a])},b.keys):j};p.m=function(b,a){return new X(a,this.keys,this.I)};p.T=!0;p.o=!0;p.p=k("b");p.k=function(b){return Mc.call(j,b)};p.t=function(){return this.keys.length};
p.J=function(b,a,d){if(z(t.call(j,a))){var b=hb.call(j,this.I),e=b.hasOwnProperty(a);b[a]=d;return z(e)?new X(this.b,this.keys,b):(d=rb.call(j,this.keys),d.push(a),new X(this.b,d,b))}else return gc.call(j,jd.call(j,Vb.call(j,a,d),K.call(j,b)),this.b)};p.u=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,b,a,j);case 3:return td.call(j,a,this.I,this.I[a],d)}c("Invalid arity: "+arguments.length)}}();sb.call(j);
X.prototype.call=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,this,a);case 3:return C.call(j,this,a,d)}c("Invalid arity: "+arguments.length)}}();function Y(b,a,d){this.b=b;this.count=a;this.r=d}p=Y.prototype;p.e=function(b,a){return rd.call(j,b,a)};p.j=function(b,a){return z(lc.call(j,a))?Bb.call(j,b,B.call(j,a,0),B.call(j,a,1)):P.call(j,vb,b,a)};
p.h=function(){var b=this;if(z(Ic.call(j,b.count))){var a=mc.call(j,b.r);return gd.call(j,function(a){return V.call(j,nd,kd.call(j,2,b.r[a]))},a)}else return j};p.m=function(b,a){return new Y(a,this.count,this.r)};p.T=!0;p.o=!0;p.p=k("b");p.k=function(b){return Mc.call(j,b)};p.t=k("count");
p.J=function(b,a,d){var b=ic.call(j,a),e=this.r[b];if(z(e)){var e=rb.call(j,e),f=hb.call(j,this.r);f[b]=e;b=sd.call(j,2,a,e);return z(b)?(e[H.call(j,b)]=d,new Y(this.b,this.count,f)):(e.push(a,d),new Y(this.b,H.call(j,this.count),f))}else return e=hb.call(j,this.r),e[b]=sb.call(j,a,d),new Y(this.b,H.call(j,this.count),e)};
p.u=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,b,a,j);case 3:var e=this.r[ic.call(j,a)],f=z(e)?sd.call(j,2,a,e):j;return z(f)?e[H.call(j,f)]:d}c("Invalid arity: "+arguments.length)}}();var ud=new Y(j,0,function(){return{}}.call(j));Y.prototype.call=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,this,a);case 3:return C.call(j,this,a,d)}c("Invalid arity: "+arguments.length)}}();
function Vb(b){for(var a=J(Array.prototype.slice.call(arguments,0),0),a=K.call(j,a),d=ud;;)if(z(a))var e=ac.call(j,a),d=fc.call(j,d,L.call(j,a),$b.call(j,a)),a=e;else return d}Vb.call(j);function vd(b){if(z(pc.call(j,b)))return b;else if(z(function(){var a=qc.call(j,b);return z(a)?a:rc.call(j,b)}())){var a=b.lastIndexOf("/");return z(Q.call(j,a,0))?Kc.call(j,b,2):Kc.call(j,b,H.call(j,a))}else return j}
function wd(b){if(z(function(){var a=qc.call(j,b);return z(a)?a:rc.call(j,b)}())){var a=b.lastIndexOf("/");return z(Cc.call(j,a,-1))?Kc.call(j,b,2,a):j}else return"\ufdd0'else"}function Z(b,a,d,e,f,h){return Vc.call(j,md([a]),fd.call(j,ed.call(j,md([d]),V.call(j,function(a){return b.call(j,a,f)},h))),md([e]))}
var $=function xd(a,d){return z(E.call(j,a))?F.call(j,"nil"):z(nc.call(j,a))?F.call(j,"#<undefined>"):z("\ufdd0'else")?Vc.call(j,z(function(){var e=ec.call(j,d,"\ufdd0'meta");return z(e)?(e=z(z(a)?a.o:a)?!0:qb.call(j,Eb,a),z(e)?hc.call(j,a):e):e}())?Vc.call(j,md(["^"]),xd.call(j,hc.call(j,a),d),md([" "])):j,z(z(z(a)?a.l:a)?!0:qb.call(j,Rb,a))?Tb.call(j,a,d):F.call(j,"#<",S.call(j,a),">")):j};
function yd(b,a){for(var d=L.call(j,b),e=new v,f=K.call(j,b);;)if(z(f)){var h=L.call(j,f);z(Ub.call(j,h,d))||e.append(" ");for(h=K.call(j,$.call(j,h,a));;)if(z(h)){var i=L.call(j,h);e.append(i);h=N.call(j,h)}else break;f=N.call(j,f)}else break;return S.call(j,e)}function zd(){return new X(j,["\ufdd0'flush-on-newline","\ufdd0'readably","\ufdd0'meta","\ufdd0'dup"],{"\ufdd0'flush-on-newline":!0,"\ufdd0'readably":!0,"\ufdd0'meta":!1,"\ufdd0'dup":!1})}
function Ad(b){var a=J(Array.prototype.slice.call(arguments,0),0);return yd.call(j,a,zd.call(j))}Y.prototype.l=!0;Y.prototype.g=function(b,a){return Z.call(j,function(b){return Z.call(j,$,""," ","",a,b)},"{",", ","}",a,b)};Rb.number=!0;Tb.number=function(b){return F.call(j,S.call(j,b))};Xb.prototype.l=!0;Xb.prototype.g=function(b,a){return Z.call(j,$,"("," ",")",a,b)};U.prototype.l=!0;U.prototype.g=function(b,a){return Z.call(j,$,"("," ",")",a,b)};Rb["boolean"]=!0;
Tb["boolean"]=function(b){return F.call(j,S.call(j,b))};Rb.string=!0;Tb.string=function(b,a){return z(qc.call(j,b))?F.call(j,S.call(j,":",function(){var a=wd.call(j,b);return z(a)?S.call(j,a,"/"):j}(),vd.call(j,b))):z(rc.call(j,b))?F.call(j,S.call(j,function(){var a=wd.call(j,b);return z(a)?S.call(j,a,"/"):j}(),vd.call(j,b))):z("\ufdd0'else")?F.call(j,z("\ufdd0'readably".call(j,a))?ia.call(j,b):b):j};W.prototype.l=!0;W.prototype.g=function(b,a){return Z.call(j,$,"["," ","]",a,b)};Nc.prototype.l=!0;
Nc.prototype.g=function(b,a){return Z.call(j,$,"("," ",")",a,b)};Rb.array=!0;Tb.array=function(b,a){return Z.call(j,$,"#<Array [",", ","]>",a,b)};Oc.prototype.l=!0;Oc.prototype.g=function(){return F.call(j,"()")};Qc.prototype.l=!0;Qc.prototype.g=function(b,a){return Z.call(j,$,"("," ",")",a,b)};X.prototype.l=!0;X.prototype.g=function(b,a){return Z.call(j,function(b){return Z.call(j,$,""," ","",a,b)},"{",", ","}",a,b)};function Bd(b){alert.call(j,b);return j}function Cd(){var b=V.call(j,function(a){return Ac.call(j,1,a)},pb.call(j,"coins").value.split(" "));return Pc.call(j,wc.call(j,b))}function Dd(){return pb.call(j,"target").value}function Ed(b){return pb.call(j,"results").innerHTML=Ad.call(j,b)}lb.call(j,pb.call(j,"do-calculation"),"click",function(){return Ed.call(j,Fd.call(j,Cd.call(j),Dd.call(j)))});function Gd(b,a){return L.call(j,id.call(j,function(b){return Dc.call(j,a,b)},b))}
var Fd=function Hd(a,d){var e=Gd.call(j,a,d);return z(D.call(j,e,0))?Bd.call(j,"No solution"):z(D.call(j,e,d))?F.call(j,e):z(Q.call(j,e,d))?cc.call(j,Hd.call(j,a,zc.call(j,d,e)),e):j};