function c(b){throw b;}var h=void 0,j=null;function aa(){return function(b){return b}}function k(b){return function(){return this[b]}}function l(b){return function(){return b}}var p,q=this;function ba(){}
function r(b){var a=typeof b;if(a=="object")if(b){if(b instanceof Array)return"array";else if(b instanceof Object)return a;var d=Object.prototype.toString.call(b);if(d=="[object Window]")return"object";if(d=="[object Array]"||typeof b.length=="number"&&typeof b.splice!="undefined"&&typeof b.propertyIsEnumerable!="undefined"&&!b.propertyIsEnumerable("splice"))return"array";if(d=="[object Function]"||typeof b.call!="undefined"&&typeof b.propertyIsEnumerable!="undefined"&&!b.propertyIsEnumerable("call"))return"function"}else return"null";
else if(a=="function"&&typeof b.call=="undefined")return"object";return a}function s(b){return typeof b=="string"}var ca="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36),da=0;function ea(b,a){function d(){}d.prototype=a.prototype;b.ba=a.prototype;b.prototype=new d};var fa={"\000":"\\0","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\x0B",'"':'\\"',"\\":"\\\\"},ga={"'":"\\'"};
function ha(b){var n;b=String(b);if(b.quote)return b.quote();else{for(var a=['"'],d=0;d<b.length;d++){var e=b.charAt(d),f=e.charCodeAt(0),g=a,i=d+1,m;if(!(m=fa[e])){if(!(f>31&&f<127))if(e in ga)e=ga[e];else if(e in fa)n=ga[e]=fa[e],e=n;else{f=e;m=e.charCodeAt(0);if(m>31&&m<127)f=e;else{if(m<256){if(f="\\x",m<16||m>256)f+="0"}else f="\\u",m<4096&&(f+="0");f+=m.toString(16).toUpperCase()}e=ga[e]=f}m=e}g[i]=m}a.push('"');return a.join("")}}
function ia(b,a){for(var d=0,e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),g=Math.max(e.length,f.length),i=0;d==0&&i<g;i++){var m=e[i]||"",n=f[i]||"",o=RegExp("(\\d*)(\\D*)","g"),t=RegExp("(\\d*)(\\D*)","g");do{var u=o.exec(m)||["","",""],G=t.exec(n)||["","",""];if(u[0].length==0&&G[0].length==0)break;d=ja(u[1].length==0?0:parseInt(u[1],10),G[1].length==0?0:parseInt(G[1],10))||ja(u[2].length==0,G[2].length==0)||ja(u[2],G[2])}while(d==
0)}return d}function ja(b,a){if(b<a)return-1;else if(b>a)return 1;return 0}function ka(b){for(var a=0,d=0;d<b.length;++d)a=31*a+b.charCodeAt(d),a%=4294967296;return a};var la,ma,na,oa,pa,qa=(pa="ScriptEngine"in q&&q.ScriptEngine()=="JScript")?q.ScriptEngineMajorVersion()+"."+q.ScriptEngineMinorVersion()+"."+q.ScriptEngineBuildVersion():"0";function v(b,a){this.f=pa?[]:"";b!=j&&this.append.apply(this,arguments)}pa?(v.prototype.P=0,v.prototype.append=function(b,a,d){a==j?this.f[this.P++]=b:(this.f.push.apply(this.f,arguments),this.P=this.f.length);return this}):v.prototype.append=function(b,a,d){this.f+=b;if(a!=j)for(var e=1;e<arguments.length;e++)this.f+=arguments[e];return this};v.prototype.clear=function(){pa?this.P=this.f.length=0:this.f=""};
v.prototype.toString=function(){if(pa){var b=this.f.join("");this.clear();b&&this.append(b);return b}else return this.f};var ra;function sa(){return q.navigator?q.navigator.userAgent:j}oa=na=ma=la=!1;var ta;if(ta=sa()){var ua=q.navigator;la=ta.indexOf("Opera")==0;ma=!la&&ta.indexOf("MSIE")!=-1;na=!la&&ta.indexOf("WebKit")!=-1;oa=!la&&!na&&ua.product=="Gecko"}var w=ma,va=oa,wa=na,xa=q.navigator,ya=(xa&&xa.platform||"").indexOf("Mac")!=-1,za;
a:{var Aa="",Ba;if(la&&q.opera)var Ca=q.opera.version,Aa=typeof Ca=="function"?Ca():Ca;else if(va?Ba=/rv\:([^\);]+)(\)|;)/:w?Ba=/MSIE\s+([^\);]+)(\)|;)/:wa&&(Ba=/WebKit\/(\S+)/),Ba)var Da=Ba.exec(sa()),Aa=Da?Da[1]:"";if(w){var Ea,Fa=q.document;Ea=Fa?Fa.documentMode:h;if(Ea>parseFloat(Aa)){za=String(Ea);break a}}za=Aa}var Ga={};function Ha(b){return Ga[b]||(Ga[b]=ia(za,b)>=0)};!w||Ha("9");w&&Ha("8");function Ia(){}Ia.prototype.V=!1;Ia.prototype.L=function(){if(!this.V)this.V=!0,this.A()};Ia.prototype.A=function(){};function Ja(b,a){this.type=b;this.currentTarget=this.target=a}ea(Ja,Ia);Ja.prototype.A=function(){delete this.type;delete this.target;delete this.currentTarget};Ja.prototype.Q=!1;Ja.prototype.fa=!0;var Ka=new Function("a","return a");function La(b,a){b&&this.M(b,a)}ea(La,Ja);p=La.prototype;p.target=j;p.relatedTarget=j;p.offsetX=0;p.offsetY=0;p.clientX=0;p.clientY=0;p.screenX=0;p.screenY=0;p.button=0;p.keyCode=0;p.charCode=0;p.ctrlKey=!1;p.altKey=!1;p.shiftKey=!1;p.metaKey=!1;p.ea=!1;p.W=j;
p.M=function(b,a){var d=this.type=b.type;Ja.call(this,d);this.target=b.target||b.srcElement;this.currentTarget=a;var e=b.relatedTarget;if(e){if(va)try{Ka(e.nodeName)}catch(f){e=j}}else if(d=="mouseover")e=b.fromElement;else if(d=="mouseout")e=b.toElement;this.relatedTarget=e;this.offsetX=b.offsetX!==h?b.offsetX:b.layerX;this.offsetY=b.offsetY!==h?b.offsetY:b.layerY;this.clientX=b.clientX!==h?b.clientX:b.pageX;this.clientY=b.clientY!==h?b.clientY:b.pageY;this.screenX=b.screenX||0;this.screenY=b.screenY||
0;this.button=b.button;this.keyCode=b.keyCode||0;this.charCode=b.charCode||(d=="keypress"?b.keyCode:0);this.ctrlKey=b.ctrlKey;this.altKey=b.altKey;this.shiftKey=b.shiftKey;this.metaKey=b.metaKey;this.ea=ya?b.metaKey:b.ctrlKey;this.state=b.state;this.W=b;delete this.fa;delete this.Q};p.A=function(){La.ba.A.call(this);this.relatedTarget=this.currentTarget=this.target=this.W=j};var Ma=Array.prototype,Na=Ma.indexOf?function(b,a,d){return Ma.indexOf.call(b,a,d)}:function(b,a,d){d=d==j?0:d<0?Math.max(0,b.length+d):d;if(s(b))return!s(a)||a.length!=1?-1:b.indexOf(a,d);for(;d<b.length;d++)if(d in b&&b[d]===a)return d;return-1};function Oa(){}var Pa=0;p=Oa.prototype;p.key=0;p.D=!1;p.S=!1;p.M=function(b,a,d,e,f,g){r(b)=="function"?this.Y=!0:b&&b.handleEvent&&r(b.handleEvent)=="function"?this.Y=!1:c(Error("Invalid listener argument"));this.N=b;this.aa=a;this.src=d;this.type=e;this.capture=!!f;this.X=g;this.S=!1;this.key=++Pa;this.D=!1};p.handleEvent=function(b){return this.Y?this.N.call(this.X||this.src,b):this.N.handleEvent.call(this.N,b)};function x(b,a){this.Z=a;this.q=[];b>this.Z&&c(Error("[goog.structs.SimplePool] Initial cannot be greater than max"));for(var d=0;d<b;d++)this.q.push(this.i?this.i():{})}ea(x,Ia);x.prototype.i=j;x.prototype.U=j;x.prototype.getObject=function(){return this.q.length?this.q.pop():this.i?this.i():{}};function Qa(b,a){b.q.length<b.Z?b.q.push(a):Ra(b,a)}function Ra(b,a){if(b.U)b.U(a);else{var d=r(a);if(d=="object"||d=="array"||d=="function")if(r(a.L)=="function")a.L();else for(var e in a)delete a[e]}}
x.prototype.A=function(){x.ba.A.call(this);for(var b=this.q;b.length;)Ra(this,b.pop());delete this.q};var Sa,Ta,Ua,Va,Wa,Xa,Ya,Za,$a,ab,bb;
(function(){function b(){return{n:0,C:0}}function a(){return[]}function d(){function b(a){return i.call(b.src,b.key,a)}return b}function e(){return new Oa}function f(){return new La}var g=pa&&!(ia(qa,"5.7")>=0),i;Xa=function(b){i=b};if(g){Sa=function(){return m.getObject()};Ta=function(b){Qa(m,b)};Ua=function(){return n.getObject()};Va=function(b){Qa(n,b)};Wa=function(){return o.getObject()};Ya=function(){Qa(o,d())};Za=function(){return t.getObject()};$a=function(b){Qa(t,b)};ab=function(){return u.getObject()};
bb=function(b){Qa(u,b)};var m=new x(0,600);m.i=b;var n=new x(0,600);n.i=a;var o=new x(0,600);o.i=d;var t=new x(0,600);t.i=e;var u=new x(0,600);u.i=f}else Sa=b,Ta=ba,Ua=a,Va=ba,Wa=d,Ya=ba,Za=e,$a=ba,ab=f,bb=ba})();function cb(b,a,d){for(var e in b)a.call(d,b[e],e,b)}function db(b){var a={},d;for(d in b)a[d]=b[d];return a};var eb={},y={},fb={},gb={};
function hb(b,a,d,e,f){if(a)if(r(a)=="array"){for(var g=0;g<a.length;g++)hb(b,a[g],d,e,f);return j}else{var e=!!e,i=y;a in i||(i[a]=Sa());i=i[a];e in i||(i[e]=Sa(),i.n++);var i=i[e],m=b[ca]||(b[ca]=++da),n;i.C++;if(i[m]){n=i[m];for(g=0;g<n.length;g++)if(i=n[g],i.N==d&&i.X==f){if(i.D)break;return n[g].key}}else n=i[m]=Ua(),i.n++;g=Wa();g.src=b;i=Za();i.M(d,g,b,a,e,f);d=i.key;g.key=d;n.push(i);eb[d]=i;fb[m]||(fb[m]=Ua());fb[m].push(i);b.addEventListener?(b==q||!b.da)&&b.addEventListener(a,g,e):b.attachEvent(a in
gb?gb[a]:gb[a]="on"+a,g);return d}else c(Error("Invalid event type"))}function ib(b,a,d,e){if(!e.O&&e.$){for(var f=0,g=0;f<e.length;f++)if(e[f].D){var i=e[f].aa;i.src=j;Ya(i);$a(e[f])}else f!=g&&(e[g]=e[f]),g++;e.length=g;e.$=!1;g==0&&(Va(e),delete y[b][a][d],y[b][a].n--,y[b][a].n==0&&(Ta(y[b][a]),delete y[b][a],y[b].n--),y[b].n==0&&(Ta(y[b]),delete y[b]))}}
function jb(b,a,d,e,f){var g=1,a=a[ca]||(a[ca]=++da);if(b[a]){b.C--;b=b[a];b.O?b.O++:b.O=1;try{for(var i=b.length,m=0;m<i;m++){var n=b[m];n&&!n.D&&(g&=kb(n,f)!==!1)}}finally{b.O--,ib(d,e,a,b)}}return Boolean(g)}
function kb(b,a){var d=b.handleEvent(a);if(b.S){var e=b.key;if(eb[e]){var f=eb[e];if(!f.D){var g=f.src,i=f.type,m=f.aa,n=f.capture;g.removeEventListener?(g==q||!g.da)&&g.removeEventListener(i,m,n):g.detachEvent&&g.detachEvent(i in gb?gb[i]:gb[i]="on"+i,m);g=g[ca]||(g[ca]=++da);m=y[i][n][g];if(fb[g]){var o=fb[g],t=Na(o,f);t>=0&&Ma.splice.call(o,t,1);o.length==0&&delete fb[g]}f.D=!0;m.$=!0;ib(i,n,g,m);delete eb[e]}}}return d}
Xa(function(b,a){if(!eb[b])return!0;var d=eb[b],e=d.type,f=y;if(!(e in f))return!0;var f=f[e],g,i;ra===h&&(ra=w&&!q.addEventListener);if(ra){var m;if(!(m=a))a:{m="window.event".split(".");for(var n=q;g=m.shift();)if(n[g]!=j)n=n[g];else{m=j;break a}m=n}g=m;m=!0 in f;n=!1 in f;if(m){if(g.keyCode<0||g.returnValue!=h)return!0;a:{var o=!1;if(g.keyCode==0)try{g.keyCode=-1;break a}catch(t){o=!0}if(o||g.returnValue==h)g.returnValue=!0}}o=ab();o.M(g,this);g=!0;try{if(m){for(var u=Ua(),G=o.currentTarget;G;G=
G.parentNode)u.push(G);i=f[!0];i.C=i.n;for(var R=u.length-1;!o.Q&&R>=0&&i.C;R--)o.currentTarget=u[R],g&=jb(i,u[R],e,!0,o);if(n){i=f[!1];i.C=i.n;for(R=0;!o.Q&&R<u.length&&i.C;R++)o.currentTarget=u[R],g&=jb(i,u[R],e,!1,o)}}else g=kb(d,o)}finally{if(u)u.length=0,Va(u);o.L();bb(o)}return g}e=new La(a,this);try{g=kb(d,e)}finally{e.L()}return g});!w||Ha("9");!va&&!w||w&&Ha("9")||va&&Ha("1.9.1");w&&Ha("9");function lb(b){return s(b)?document.getElementById(b):b};function z(b){return b!=j&&b!==!1}function mb(b,a){var d=b[r.call(j,a)];return z(d)?d:(d=b._,z(d)?d:!1)}function nb(b){return Array.prototype.slice.call(b)}function ob(b){return Array.prototype.slice.call(arguments)}
var A=function pb(a){return z(z(a)?a.t:a)?a.t(a):function(){var d=pb[r.call(j,a)];return z(d)?d:pb._}().call(j,a)},rb=function qb(a,d){return z(z(a)?a.j:a)?a.j(a,d):function(){var d=qb[r.call(j,a)];return z(d)?d:qb._}().call(j,a,d)},B=function(){function b(b,a,g){return z(z(b)?b.K:b)?b.K(b,a,g):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a,g)}function a(b,a){return z(z(b)?b.K:b)?b.K(b,a):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a)}var d=j;return d=function(d,
f,g){switch(arguments.length){case 2:return a.call(this,d,f);case 3:return b.call(this,d,f,g)}c("Invalid arity: "+arguments.length)}}(),tb=function sb(a){return z(z(a)?a.v:a)?a.v(a):function(){var d=sb[r.call(j,a)];return z(d)?d:sb._}().call(j,a)},vb=function ub(a){return z(z(a)?a.w:a)?a.w(a):function(){var d=ub[r.call(j,a)];return z(d)?d:ub._}().call(j,a)},C=function(){function b(b,a,g){return z(z(b)?b.u:b)?b.u(b,a,g):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a,g)}function a(b,
a){return z(z(b)?b.u:b)?b.u(b,a):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a)}var d=j;return d=function(d,f,g){switch(arguments.length){case 2:return a.call(this,d,f);case 3:return b.call(this,d,f,g)}c("Invalid arity: "+arguments.length)}}(),xb=function wb(a,d,e){return z(z(a)?a.J:a)?a.J(a,d,e):function(){var d=wb[r.call(j,a)];return z(d)?d:wb._}().call(j,a,d,e)},yb={},zb={},Ab={},Cb=function Bb(a){return z(z(a)?a.p:a)?a.b:function(){var d=Bb[r.call(j,a)];return z(d)?d:Bb._}().call(j,
a)},Eb=function Db(a,d){return z(z(a)?a.m:a)?a.m(a,d):function(){var d=Db[r.call(j,a)];return z(d)?d:Db._}().call(j,a,d)},Fb=function(){function b(b,a,g){return z(z(b)?b.G:b)?b.G(b,a,g):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a,g)}function a(b,a){return z(z(b)?b.G:b)?b.G(b,a):function(){var a=d[r.call(j,b)];return z(a)?a:d._}().call(j,b,a)}var d=j;return d=function(d,f,g){switch(arguments.length){case 2:return a.call(this,d,f);case 3:return b.call(this,d,f,g)}c("Invalid arity: "+
arguments.length)}}(),Hb=function Gb(a,d){return z(z(a)?a.e:a)?a.e(a,d):function(){var d=Gb[r.call(j,a)];return z(d)?d:Gb._}().call(j,a,d)},Jb=function Ib(a){return z(z(a)?a.k:a)?a.k(a):function(){var d=Ib[r.call(j,a)];return z(d)?d:Ib._}().call(j,a)},Lb=function Kb(a){return z(z(a)?a.h:a)?a.h(a):function(){var d=Kb[r.call(j,a)];return z(d)?d:Kb._}().call(j,a)},Mb={},Nb={},Pb=function Ob(a,d){return z(z(a)?a.g:a)?a.g(a,d):function(){var d=Ob[r.call(j,a)];return z(d)?d:Ob._}().call(j,a,d)};
function Qb(b,a){return b===a}function D(b,a){return Hb.call(j,b,a)}function E(b){return Qb.call(j,b,j)}Hb["null"]=function(b,a){return E.call(j,a)};rb["null"]=function(b,a){return F.call(j,a)};tb["null"]=l(j);vb["null"]=function(){return F.call(j)};Eb["null"]=l(j);yb["null"]=!0;B["null"]=function(){return function(b,a,d){switch(arguments.length){case 2:return j;case 3:return d}c("Invalid arity: "+arguments.length)}}();Ab["null"]=!0;Cb["null"]=l(j);
Fb["null"]=function(){return function(b,a,d){switch(arguments.length){case 2:return a.call(j);case 3:return d}c("Invalid arity: "+arguments.length)}}();Jb["null"]=l(0);A["null"]=l(0);xb["null"]=function(b,a,d){return Rb.call(j,a,d)};C["null"]=function(){return function(b,a,d){switch(arguments.length){case 2:return j;case 3:return d}c("Invalid arity: "+arguments.length)}}();Date.prototype.e=function(b,a){return Qb.call(j,b.toString,a.toString)};Jb.number=aa();
Hb.number=function(b,a){return Qb.call(j,b,a)};function H(b){return b+1}function Sb(b,a){return b<a}
var I=function(){return function(b,a,d,e){switch(arguments.length){case 2:var f;a:if(z(D.call(j,0,A.call(j,b))))f=a.call(j);else for(var g=B.call(j,b,0),i=1;;)if(z(Sb.call(j,i,A.call(j,b))))g=a.call(j,g,B.call(j,b,i)),i=H.call(j,i);else{f=g;break a}return f;case 3:a:{f=d;for(i=0;;)if(z(Sb.call(j,i,A.call(j,b))))f=a.call(j,f,B.call(j,b,i)),i=H.call(j,i);else{g=f;break a}}return g;case 4:a:{f=d;for(g=e;;)if(z(Sb.call(j,g,A.call(j,b))))f=a.call(j,f,B.call(j,b,g)),g=H.call(j,g);else{i=f;break a}}return i}c("Invalid arity: "+
arguments.length)}}();function Tb(b,a){this.s=b;this.B=a}p=Tb.prototype;p.G=function(){return function(b,a,d){switch(arguments.length){case 2:return I.call(j,this.s,a,this.s[this.B],H.call(j,this.B));case 3:return I.call(j,this.s,a,d,this.B)}c("Invalid arity: "+arguments.length)}}();p.e=function(b,a){return Ub.call(j,b,a)};p.z=!0;p.v=function(){return this.s[this.B]};p.w=function(){return z(Sb.call(j,H.call(j,this.B),A.call(j,this.s)))?new Tb(this.s,H.call(j,this.B)):F.call(j)};p.h=aa();
function Vb(b,a){return z(D.call(j,0,A.call(j,b)))?j:new Tb(b,a)}function J(b,a){return Vb.call(j,b,a)}Fb.array=function(){return function(b,a,d){switch(arguments.length){case 2:return I.call(j,b,a);case 3:return I.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();C.array=function(){return function(b,a,d){switch(arguments.length){case 2:return b[a];case 3:return B.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();
B.array=function(){return function(b,a,d){switch(arguments.length){case 2:return z(Sb.call(j,a,b.length))?b[a]:j;case 3:return z(Sb.call(j,a,b.length))?b[a]:d}c("Invalid arity: "+arguments.length)}}();A.array=function(b){return b.length};Lb.array=function(b){return J.call(j,b,0)};function K(b){return z(b)?Lb.call(j,b):j}function L(b){b=K.call(j,b);return z(b)?tb.call(j,b):j}function M(b){return vb.call(j,K.call(j,b))}function N(b){return z(b)?K.call(j,M.call(j,b)):j}
function Wb(b){return L.call(j,N.call(j,b))}function Xb(b){return N.call(j,N.call(j,b))}A._=function(b){for(var b=K.call(j,b),a=0;;)if(z(b))b=N.call(j,b),a=H.call(j,a);else return a};Hb._=function(b,a){return Qb.call(j,b,a)};function Yb(b){return z(b)?!1:!0}
var Zb=function(){function b(b,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(z(g))var i=a.call(j,b,e),m=L.call(j,g),g=N.call(j,g),b=i,e=m;else return a.call(j,b,e)}var a=j,a=function(a,e,f){switch(arguments.length){case 2:return rb.call(j,a,e);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}();function $b(b){return A.call(j,b)}
var ac=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,b,a);case 3:return C.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}(),bc=function(){function b(b,e,f,g){for(var i=J(Array.prototype.slice.call(arguments,3),0);;){var m=a.call(j,b,e,f);if(z(i))var n=L.call(j,i),o=Wb.call(j,i),i=Xb.call(j,i),b=m,e=n,f=o;else return m}}var a=j,a=function(a,e,f,g){switch(arguments.length){case 3:return xb.call(j,a,e,f);default:return b.apply(this,arguments)}c("Invalid arity: "+
arguments.length)};a.c=3;a.a=function(a){var e=L(a),f=L(N(a)),g=L(N(N(a))),a=M(N(N(a)));return b.call(j,e,f,g,a)};return a}();function cc(b,a){return Eb.call(j,b,a)}function dc(b){return Cb.call(j,b)}function ec(b){return Jb.call(j,b)}function fc(b){return z(z(b)?b.z:b)?!0:mb.call(j,Mb,b)}function gc(b){return z(E.call(j,b))?!1:z(z(b)?b.T:b)?!0:mb.call(j,yb,b)}function hc(b){return z(z(b)?b.ca:b)?!0:mb.call(j,zb,b)}
function ic(b){var a=ob.call(j);cb.call(j,b,function(b,e){return a.push(e)});return a}function jc(b){return h===b}function kc(b){return z(b)?!0:!1}function lc(b){var a=s.call(j,b);return z(a)?Yb.call(j,function(){var a=D.call(j,b.charAt(0),"\ufdd0");return z(a)?a:D.call(j,b.charAt(0),"\ufdd1")}()):a}function mc(b){var a=s.call(j,b);return z(a)?D.call(j,b.charAt(0),"\ufdd0"):a}function nc(b){var a=s.call(j,b);return z(a)?D.call(j,b.charAt(0),"\ufdd1"):a}
var O=function(){return function(b,a,d){switch(arguments.length){case 2:return Fb.call(j,a,b);case 3:return Fb.call(j,d,b,a)}c("Invalid arity: "+arguments.length)}}(),oc=function(){return function(b,a,d){switch(arguments.length){case 2:var e=K.call(j,a);return z(e)?O.call(j,b,L.call(j,e),N.call(j,e)):b.call(j);case 3:a:for(var f=a,g=K.call(j,d);;)if(z(g))f=b.call(j,f,L.call(j,g)),g=N.call(j,g);else{e=f;break a}return e}c("Invalid arity: "+arguments.length)}}();
Fb._=function(){return function(b,a,d){switch(arguments.length){case 2:return oc.call(j,a,b);case 3:return oc.call(j,a,d,b)}c("Invalid arity: "+arguments.length)}}();
var pc=function(){function b(b,e,f){var g=J(Array.prototype.slice.call(arguments,2),0);return O.call(j,a,a.call(j,b,e),g)}var a=j,a=function(a,e,f){switch(arguments.length){case 0:return 0;case 1:return a;case 2:return a+e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),qc=function(){function b(b,e,f){var g=J(Array.prototype.slice.call(arguments,2),0);return O.call(j,a,a.call(j,b,
e),g)}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return-a;case 2:return a-e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),rc=function(){function b(b,e,f){var g=J(Array.prototype.slice.call(arguments,2),0);return O.call(j,a,a.call(j,b,e),g)}var a=j,a=function(a,e,f){switch(arguments.length){case 0:return 1;case 1:return a;case 2:return a*e;default:return b.apply(this,
arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),P=function(){function b(b,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(z(a.call(j,b,e)))if(z(N.call(j,g)))var i=e,m=L.call(j,g),g=N.call(j,g),b=i,e=m;else return a.call(j,e,L.call(j,g));else return!1}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a<e;default:return b.apply(this,arguments)}c("Invalid arity: "+
arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),sc=function(){function b(b,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(z(a.call(j,b,e)))if(z(N.call(j,g)))var i=e,m=L.call(j,g),g=N.call(j,g),b=i,e=m;else return a.call(j,e,L.call(j,g));else return!1}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a<=e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=
function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),tc=function(){function b(b,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(z(a.call(j,b,e)))if(z(N.call(j,g)))var i=e,m=L.call(j,g),g=N.call(j,g),b=i,e=m;else return a.call(j,e,L.call(j,g));else return!1}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a>e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),
a=M(N(a));return b.call(j,e,f,a)};return a}(),uc=function(){function b(b,e,f){for(var g=J(Array.prototype.slice.call(arguments,2),0);;)if(z(a.call(j,b,e)))if(z(N.call(j,g)))var i=e,m=L.call(j,g),g=N.call(j,g),b=i,e=m;else return a.call(j,e,L.call(j,g));else return!1}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!0;case 2:return a>=e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,
f,a)};return a}();function vc(b){return qc.call(j,b,1)}var wc=function(){function b(b,e,f){var g=J(Array.prototype.slice.call(arguments,2),0);return O.call(j,a,a.call(j,b,e),g)}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return a;case 2:return a>e?a:e;default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}();function xc(b,a){return b^a}function yc(b,a){return b<<a}
function zc(b,a){return b>>a}function Ac(b){return P.call(j,0,b)}function Bc(b,a){for(var d=a,e=K.call(j,b);;)if(z(function(){var a=e;return z(a)?Ac.call(j,d):a}()))var f=vc.call(j,d),g=N.call(j,e),d=f,e=g;else return e}B._=function(){return function(b,a,d){switch(arguments.length){case 2:var e;var f=Bc.call(j,b,a);z(f)?e=L.call(j,f):c("Index out of bounds");return e;case 3:return e=Bc.call(j,b,a),z(e)?L.call(j,e):d}c("Invalid arity: "+arguments.length)}}();
var Q=function(){function b(b,e){var f=J(Array.prototype.slice.call(arguments,1),0);return function(b,d){for(;;)if(z(d))var e=b.append(a.call(j,L.call(j,d))),f=N.call(j,d),b=e,d=f;else return a.call(j,b)}.call(j,new v(a.call(j,b)),f)}var a=j,a=function(a,e){switch(arguments.length){case 0:return"";case 1:return z(E.call(j,a))?"":a.toString();default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=1;a.a=function(a){var e=L(a),a=M(a);return b.call(j,e,a)};return a}(),Cc=function(){return function(b,
a,d){switch(arguments.length){case 2:return b.substring(a);case 3:return b.substring(a,d)}c("Invalid arity: "+arguments.length)}}();function Ub(b,a){return kc.call(j,z(fc.call(j,a))?function(){for(var d=K.call(j,b),e=K.call(j,a);;)if(z(E.call(j,d)))return E.call(j,e);else if(z(E.call(j,e)))return!1;else if(z(D.call(j,L.call(j,d),L.call(j,e))))d=N.call(j,d),e=N.call(j,e);else return z("\ufdd0'else")?!1:j}():j)}
function Dc(b,a){return xc.call(j,b,pc.call(j,a,2654435769,yc.call(j,b,6),zc.call(j,b,2)))}function Ec(b){return O.call(j,function(a,b){return Dc.call(j,a,ec.call(j,b))},ec.call(j,L.call(j,b)),N.call(j,b))}function Fc(b,a,d,e){this.b=b;this.H=a;this.F=d;this.count=e}p=Fc.prototype;p.e=function(b,a){return Ub.call(j,b,a)};p.j=function(b,a){return new Fc(this.b,a,b,H.call(j,this.count))};p.v=k("H");p.w=k("F");p.h=aa();p.m=function(b,a){return new Fc(a,this.H,this.F,this.count)};p.o=!0;p.p=k("b");
p.k=function(b){return Ec.call(j,b)};p.t=k("count");p.z=!0;function Gc(b){this.b=b}p=Gc.prototype;p.e=function(b,a){return Ub.call(j,b,a)};p.j=function(b,a){return new Fc(this.b,a,j,1)};p.v=l(j);p.w=l(j);p.h=l(j);p.m=function(b,a){return new Gc(a)};p.o=!0;p.p=k("b");p.k=function(b){return Ec.call(j,b)};p.t=l(0);p.z=!0;var Hc=new Gc(j);function Ic(b){return O.call(j,Zb,Hc,b)}function F(b){var a=J(Array.prototype.slice.call(arguments,0),0);return O.call(j,Zb,Hc,Ic.call(j,a))}
function Jc(b,a,d){this.b=b;this.H=a;this.F=d}p=Jc.prototype;p.h=aa();p.k=function(b){return Ec.call(j,b)};p.e=function(b,a){return Ub.call(j,b,a)};p.z=!0;p.j=function(b,a){return new Jc(j,a,b)};p.v=k("H");p.w=function(){return z(E.call(j,this.F))?Hc:this.F};p.o=!0;p.p=k("b");p.m=function(b,a){return new Jc(a,this.H,this.F)};function S(b,a){return new Jc(j,b,a)}
Fb.string=function(){return function(b,a,d){switch(arguments.length){case 2:return I.call(j,b,a);case 3:return I.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();C.string=function(){return function(b,a,d){switch(arguments.length){case 2:return B.call(j,b,a);case 3:return B.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();
B.string=function(){return function(b,a,d){switch(arguments.length){case 2:return z(P.call(j,a,A.call(j,b)))?b.charAt(a):j;case 3:return z(P.call(j,a,A.call(j,b)))?b.charAt(a):d}c("Invalid arity: "+arguments.length)}}();A.string=function(b){return b.length};Lb.string=function(b){return Vb.call(j,b,0)};Jb.string=function(b){return ka.call(j,b)};
String.prototype.call=function(){return function(b,a,d){switch(arguments.length){case 2:return ac.call(j,a,this.toString());case 3:return ac.call(j,a,this.toString(),d)}c("Invalid arity: "+arguments.length)}}();function Kc(b){var a=b.x;return z(b.R)?a:(b.x=a.call(j),b.R=!0,b.x)}function T(b,a,d){this.b=b;this.R=a;this.x=d}p=T.prototype;p.h=function(b){return K.call(j,Kc.call(j,b))};p.k=function(b){return Ec.call(j,b)};p.e=function(b,a){return Ub.call(j,b,a)};p.z=!0;
p.j=function(b,a){return S.call(j,a,b)};p.v=function(b){return L.call(j,Kc.call(j,b))};p.w=function(b){return M.call(j,Kc.call(j,b))};p.o=!0;p.p=k("b");p.m=function(b,a){return new T(a,this.R,this.x)};function U(b){for(var a=ob.call(j);;)if(z(K.call(j,b)))a.push(L.call(j,b)),b=N.call(j,b);else return a}function Lc(b,a){for(var d=b,e=a,f=0;;)if(z(function(){var a=Ac.call(j,e);return z(a)?K.call(j,d):a}()))var g=N.call(j,d),i=vc.call(j,e),f=H.call(j,f),d=g,e=i;else return f}
var Nc=function Mc(a){return z(E.call(j,a))?j:z(E.call(j,N.call(j,a)))?K.call(j,L.call(j,a)):z("\ufdd0'else")?S.call(j,L.call(j,a),Mc.call(j,N.call(j,a))):j},Oc=function(){function b(a,b,d){var e=J(Array.prototype.slice.call(arguments,2),0);return function t(a,b){return new T(j,!1,function(){var d=K.call(j,a);return z(d)?S.call(j,L.call(j,d),t.call(j,M.call(j,d),b)):z(b)?t.call(j,L.call(j,b),N.call(j,b)):j})}.call(j,f.call(j,a,b),e)}function a(a,b){return new T(j,!1,function(){var d=K.call(j,a);return z(d)?
S.call(j,L.call(j,d),f.call(j,M.call(j,d),b)):b})}function d(a){return new T(j,!1,function(){return a})}function e(){return new T(j,!1,l(j))}var f=j,f=function(g,f,m){switch(arguments.length){case 0:return e.call(this);case 1:return d.call(this,g);case 2:return a.call(this,g,f);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};f.c=2;f.a=function(a){var d=L(a),e=L(N(a)),a=M(N(a));return b.call(j,d,e,a)};return f}(),Pc=function(){function b(a,b,f,g,i){var m=J(Array.prototype.slice.call(arguments,
4),0);return S.call(j,a,S.call(j,b,S.call(j,f,S.call(j,g,Nc.call(j,m)))))}var a=j,a=function(a,e,f,g,i){switch(arguments.length){case 1:return K.call(j,a);case 2:return S.call(j,a,e);case 3:return S.call(j,a,S.call(j,e,f));case 4:return S.call(j,a,S.call(j,e,S.call(j,f,g)));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=4;a.a=function(a){var e=L(a),f=L(N(a)),g=L(N(N(a))),i=L(N(N(N(a)))),a=M(N(N(N(a))));return b.call(j,e,f,g,i,a)};return a}(),Qc=function(){function b(a,
b,f,g,i,m){var n=J(Array.prototype.slice.call(arguments,5),0),n=S.call(j,b,S.call(j,f,S.call(j,g,S.call(j,i,Nc.call(j,n))))),o=a.c;return z(a.a)?z(sc.call(j,Lc.call(j,n,o),o))?a.apply(a,U.call(j,n)):a.a(n):a.apply(a,U.call(j,n))}var a=j,a=function(a,e,f,g,i,m){switch(arguments.length){case 2:var n=a,o=e,t=n.c;return z(n.a)?z(sc.call(j,Lc.call(j,o,t),t))?n.apply(n,U.call(j,o)):n.a(o):n.apply(n,U.call(j,o));case 3:return n=a,o=Pc.call(j,e,f),t=n.c,z(n.a)?z(sc.call(j,Lc.call(j,o,t),t))?n.apply(n,U.call(j,
o)):n.a(o):n.apply(n,U.call(j,o));case 4:return n=a,o=Pc.call(j,e,f,g),t=n.c,z(n.a)?z(sc.call(j,Lc.call(j,o,t),t))?n.apply(n,U.call(j,o)):n.a(o):n.apply(n,U.call(j,o));case 5:return n=a,o=Pc.call(j,e,f,g,i),t=n.c,z(n.a)?z(sc.call(j,Lc.call(j,o,t),t))?n.apply(n,U.call(j,o)):n.a(o):n.apply(n,U.call(j,o));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=5;a.a=function(a){var e=L(a),f=L(N(a)),g=L(N(N(a))),i=L(N(N(N(a)))),m=L(N(N(N(N(a))))),a=M(N(N(N(N(a)))));return b.call(j,
e,f,g,i,m,a)};return a}(),Rc=function(){function b(a,b,f){var g=J(Array.prototype.slice.call(arguments,2),0);return Yb.call(j,Qc.call(j,D,a,b,g))}var a=j,a=function(a,e,f){switch(arguments.length){case 1:return!1;case 2:return Yb.call(j,D.call(j,a,e));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}();
function Sc(b,a){for(;;)if(z(E.call(j,K.call(j,a))))return!0;else if(z(b.call(j,L.call(j,a))))var d=b,e=N.call(j,a),b=d,a=e;else return z("\ufdd0'else")?!1:j}function Tc(b){return b}
var V=function(){function b(a,b,d,e,o){var t=J(Array.prototype.slice.call(arguments,4),0);return f.call(j,function(b){return Qc.call(j,a,b)},function G(a){return new T(j,!1,function(){var b=f.call(j,K,a);return z(Sc.call(j,Tc,b))?S.call(j,f.call(j,L,b),G.call(j,f.call(j,M,b))):j})}.call(j,Zb.call(j,t,e,d,b)))}function a(a,b,d,e){return new T(j,!1,function(){var o=K.call(j,b),t=K.call(j,d),u=K.call(j,e);return z(z(o)?z(t)?u:t:o)?S.call(j,a.call(j,L.call(j,o),L.call(j,t),L.call(j,u)),f.call(j,a,M.call(j,
o),M.call(j,t),M.call(j,u))):j})}function d(a,b,d){return new T(j,!1,function(){var e=K.call(j,b),o=K.call(j,d);return z(z(e)?o:e)?S.call(j,a.call(j,L.call(j,e),L.call(j,o)),f.call(j,a,M.call(j,e),M.call(j,o))):j})}function e(a,b){return new T(j,!1,function(){var d=K.call(j,b);return z(d)?S.call(j,a.call(j,L.call(j,d)),f.call(j,a,M.call(j,d))):j})}var f=j,f=function(f,i,m,n,o){switch(arguments.length){case 2:return e.call(this,f,i);case 3:return d.call(this,f,i,m);case 4:return a.call(this,f,i,m,
n);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};f.c=4;f.a=function(a){var d=L(a),e=L(N(a)),f=L(N(N(a))),o=L(N(N(N(a)))),a=M(N(N(N(a))));return b.call(j,d,e,f,o,a)};return f}(),Vc=function Uc(a,d){return new T(j,!1,function(){if(z(Ac.call(j,a))){var e=K.call(j,d);return z(e)?S.call(j,L.call(j,e),Uc.call(j,vc.call(j,a),M.call(j,e))):j}else return j})};
function Wc(b,a){function d(a,b){for(;;){var d=K.call(j,b);if(z(function(){var b=Ac.call(j,a);return z(b)?d:b}()))var i=vc.call(j,a),m=M.call(j,d),a=i,b=m;else return d}}return new T(j,!1,function(){return d.call(j,b,a)})}
var Xc=function(){function b(b){return new T(j,!1,function(){return S.call(j,b,a.call(j,b))})}var a=j;return a=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return Vc.call(j,d,a.call(j,e))}c("Invalid arity: "+arguments.length)}}(),Yc=function(){function b(a,b,g){var i=J(Array.prototype.slice.call(arguments,2),0);return new T(j,!1,function(){var g=V.call(j,K,Zb.call(j,i,b,a));return z(Sc.call(j,Tc,g))?Oc.call(j,V.call(j,L,g),Qc.call(j,d,V.call(j,M,g))):j})}function a(a,
b){return new T(j,!1,function(){var g=K.call(j,a),i=K.call(j,b);return z(z(g)?i:g)?S.call(j,L.call(j,g),S.call(j,L.call(j,i),d.call(j,M.call(j,g),M.call(j,i)))):j})}var d=j,d=function(d,f,g){switch(arguments.length){case 2:return a.call(this,d,f);default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};d.c=2;d.a=function(a){var d=L(a),g=L(N(a)),a=M(N(a));return b.call(j,d,g,a)};return d}();function Zc(b,a){return Wc.call(j,1,Yc.call(j,Xc.call(j,b),a))}
function $c(b){return function d(b,f){return new T(j,!1,function(){var g=K.call(j,b);return z(g)?S.call(j,L.call(j,g),d.call(j,M.call(j,g),f)):z(K.call(j,f))?d.call(j,L.call(j,f),M.call(j,f)):j})}.call(j,j,b)}
var ad=function(){function b(a,b,f){var g=J(Array.prototype.slice.call(arguments,2),0);return $c.call(j,Qc.call(j,V,a,b,g))}var a=j,a=function(a,e,f){switch(arguments.length){case 2:return $c.call(j,V.call(j,a,e));default:return b.apply(this,arguments)}c("Invalid arity: "+arguments.length)};a.c=2;a.a=function(a){var e=L(a),f=L(N(a)),a=M(N(a));return b.call(j,e,f,a)};return a}(),cd=function bd(a,d){return new T(j,!1,function(){var e=K.call(j,d);if(z(e)){var f=L.call(j,e),e=M.call(j,e);return z(a.call(j,
f))?S.call(j,f,bd.call(j,a,e)):bd.call(j,a,e)}else return j})};function dd(b,a){return O.call(j,rb,b,a)}
var ed=function(){function b(a,b,g,i){return new T(j,!1,function(){var m=K.call(j,i);if(z(m)){var n=Vc.call(j,a,m);return z(D.call(j,a,$b.call(j,n)))?S.call(j,n,d.call(j,a,b,g,Wc.call(j,b,m))):F.call(j,Vc.call(j,a,Oc.call(j,n,g)))}else return j})}function a(a,b,g){return new T(j,!1,function(){var i=K.call(j,g);if(z(i)){var m=Vc.call(j,a,i);return z(D.call(j,a,$b.call(j,m)))?S.call(j,m,d.call(j,a,b,Wc.call(j,b,i))):j}else return j})}var d=j;return d=function(e,f,g,i){switch(arguments.length){case 2:return d.call(j,
e,e,f);case 3:return a.call(this,e,f,g);case 4:return b.call(this,e,f,g,i)}c("Invalid arity: "+arguments.length)}}();function W(b,a){this.b=b;this.d=a}p=W.prototype;p.e=function(b,a){return Ub.call(j,b,a)};p.j=function(b,a){var d=nb.call(j,this.d);d.push(a);return new W(this.b,d)};p.h=function(){var b=this;return z(tc.call(j,b.d.length,0))?function d(e){return new T(j,!1,function(){return z(P.call(j,e,b.d.length))?S.call(j,b.d[e],d.call(j,H.call(j,e))):j})}.call(j,0):j};p.ca=!0;
p.m=function(b,a){return new W(a,this.d)};p.K=function(){function b(a,b,f){var g=this;return z(function(){var a=sc.call(j,0,b);return z(a)?P.call(j,b,g.d.length):a}())?g.d[b]:f}function a(a,b){var f=this;return z(function(){var a=sc.call(j,0,b);return z(a)?P.call(j,b,f.d.length):a}())?f.d[b]:j}return function(d,e,f){switch(arguments.length){case 2:return a.call(this,0,e);case 3:return b.call(this,0,e,f)}c("Invalid arity: "+arguments.length)}}();p.o=!0;p.p=k("b");
p.G=function(){return function(b,a,d){switch(arguments.length){case 2:return I.call(j,this.d,a);case 3:return I.call(j,this.d,a,d)}c("Invalid arity: "+arguments.length)}}();p.k=function(b){return Ec.call(j,b)};p.t=function(){return this.d.length};p.z=!0;p.J=function(b,a,d){b=nb.call(j,this.d);b[a]=d;return new W(this.b,b)};p.u=function(){return function(b,a,d){switch(arguments.length){case 2:return B.call(j,b,a,j);case 3:return B.call(j,b,a,d)}c("Invalid arity: "+arguments.length)}}();
var fd=new W(j,ob.call(j));function gd(b){return new W(j,b)}W.prototype.call=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,this,a);case 3:return C.call(j,this,a,d)}c("Invalid arity: "+arguments.length)}}();function hd(b){return O.call(j,Zb,fd,b)}function id(b){var a=J(Array.prototype.slice.call(arguments,0),0);return hd.call(j,a)}function jd(){}jd.prototype.e=l(!1);var kd=new jd;
function ld(b,a){return kc.call(j,z(gc.call(j,a))?z(D.call(j,$b.call(j,b),$b.call(j,a)))?Sc.call(j,Tc,V.call(j,function(b){return D.call(j,ac.call(j,a,L.call(j,b),kd),Wb.call(j,b))},b)):j:j)}function md(b,a,d){for(var e=d.length,f=0;;)if(z(P.call(j,f,e)))if(z(D.call(j,a,d[f])))return f;else f=pc.call(j,f,b);else return j}
var nd=function(){function b(a,b,f,g){return z(function(){var f=s.call(j,a);return z(f)?b.hasOwnProperty(a):f}())?f:g}var a=j;return a=function(d,e,f,g){switch(arguments.length){case 2:return a.call(j,d,e,!0,!1);case 4:return b.call(this,d,e,f,g)}c("Invalid arity: "+arguments.length)}}();function X(b,a,d){this.b=b;this.keys=a;this.I=d}p=X.prototype;p.e=function(b,a){return ld.call(j,b,a)};p.j=function(b,a){return z(hc.call(j,a))?xb.call(j,b,B.call(j,a,0),B.call(j,a,1)):O.call(j,rb,b,a)};
p.h=function(){var b=this;return z(Ac.call(j,b.keys.length))?V.call(j,function(a){return id.call(j,a,b.I[a])},b.keys):j};p.m=function(b,a){return new X(a,this.keys,this.I)};p.T=!0;p.o=!0;p.p=k("b");p.k=function(b){return Ec.call(j,b)};p.t=function(){return this.keys.length};
p.J=function(b,a,d){if(z(s.call(j,a))){var b=db.call(j,this.I),e=b.hasOwnProperty(a);b[a]=d;return z(e)?new X(this.b,this.keys,b):(d=nb.call(j,this.keys),d.push(a),new X(this.b,d,b))}else return cc.call(j,dd.call(j,Rb.call(j,a,d),K.call(j,b)),this.b)};p.u=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,b,a,j);case 3:return nd.call(j,a,this.I,this.I[a],d)}c("Invalid arity: "+arguments.length)}}();ob.call(j);
X.prototype.call=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,this,a);case 3:return C.call(j,this,a,d)}c("Invalid arity: "+arguments.length)}}();function Y(b,a,d){this.b=b;this.count=a;this.r=d}p=Y.prototype;p.e=function(b,a){return ld.call(j,b,a)};p.j=function(b,a){return z(hc.call(j,a))?xb.call(j,b,B.call(j,a,0),B.call(j,a,1)):O.call(j,rb,b,a)};
p.h=function(){var b=this;if(z(Ac.call(j,b.count))){var a=ic.call(j,b.r);return ad.call(j,function(a){return V.call(j,hd,ed.call(j,2,b.r[a]))},a)}else return j};p.m=function(b,a){return new Y(a,this.count,this.r)};p.T=!0;p.o=!0;p.p=k("b");p.k=function(b){return Ec.call(j,b)};p.t=k("count");
p.J=function(b,a,d){var b=ec.call(j,a),e=this.r[b];if(z(e)){var e=nb.call(j,e),f=db.call(j,this.r);f[b]=e;b=md.call(j,2,a,e);return z(b)?(e[H.call(j,b)]=d,new Y(this.b,this.count,f)):(e.push(a,d),new Y(this.b,H.call(j,this.count),f))}else return e=db.call(j,this.r),e[b]=ob.call(j,a,d),new Y(this.b,H.call(j,this.count),e)};
p.u=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,b,a,j);case 3:var e=this.r[ec.call(j,a)],f=z(e)?md.call(j,2,a,e):j;return z(f)?e[H.call(j,f)]:d}c("Invalid arity: "+arguments.length)}}();var od=new Y(j,0,function(){return{}}.call(j));Y.prototype.call=function(){return function(b,a,d){switch(arguments.length){case 2:return C.call(j,this,a);case 3:return C.call(j,this,a,d)}c("Invalid arity: "+arguments.length)}}();
function Rb(b){for(var a=J(Array.prototype.slice.call(arguments,0),0),a=K.call(j,a),d=od;;)if(z(a))var e=Xb.call(j,a),d=bc.call(j,d,L.call(j,a),Wb.call(j,a)),a=e;else return d}Rb.call(j);function pd(b){if(z(lc.call(j,b)))return b;else if(z(function(){var a=mc.call(j,b);return z(a)?a:nc.call(j,b)}())){var a=b.lastIndexOf("/");return z(P.call(j,a,0))?Cc.call(j,b,2):Cc.call(j,b,H.call(j,a))}else return j}
function qd(b){if(z(function(){var a=mc.call(j,b);return z(a)?a:nc.call(j,b)}())){var a=b.lastIndexOf("/");return z(tc.call(j,a,-1))?Cc.call(j,b,2,a):j}else return"\ufdd0'else"}function Z(b,a,d,e,f,g){return Oc.call(j,gd([a]),$c.call(j,Zc.call(j,gd([d]),V.call(j,function(a){return b.call(j,a,f)},g))),gd([e]))}
var $=function rd(a,d){return z(E.call(j,a))?F.call(j,"nil"):z(jc.call(j,a))?F.call(j,"#<undefined>"):z("\ufdd0'else")?Oc.call(j,z(function(){var e=ac.call(j,d,"\ufdd0'meta");return z(e)?(e=z(z(a)?a.o:a)?!0:mb.call(j,Ab,a),z(e)?dc.call(j,a):e):e}())?Oc.call(j,gd(["^"]),rd.call(j,dc.call(j,a),d),gd([" "])):j,z(z(z(a)?a.l:a)?!0:mb.call(j,Nb,a))?Pb.call(j,a,d):F.call(j,"#<",Q.call(j,a),">")):j};
function sd(b,a){for(var d=L.call(j,b),e=new v,f=K.call(j,b);;)if(z(f)){var g=L.call(j,f);z(Qb.call(j,g,d))||e.append(" ");for(g=K.call(j,$.call(j,g,a));;)if(z(g)){var i=L.call(j,g);e.append(i);g=N.call(j,g)}else break;f=N.call(j,f)}else break;return Q.call(j,e)}function td(){return new X(j,["\ufdd0'flush-on-newline","\ufdd0'readably","\ufdd0'meta","\ufdd0'dup"],{"\ufdd0'flush-on-newline":!0,"\ufdd0'readably":!0,"\ufdd0'meta":!1,"\ufdd0'dup":!1})}
function ud(b){var a=J(Array.prototype.slice.call(arguments,0),0);return sd.call(j,a,td.call(j))}Y.prototype.l=!0;Y.prototype.g=function(b,a){return Z.call(j,function(b){return Z.call(j,$,""," ","",a,b)},"{",", ","}",a,b)};Nb.number=!0;Pb.number=function(b){return F.call(j,Q.call(j,b))};Tb.prototype.l=!0;Tb.prototype.g=function(b,a){return Z.call(j,$,"("," ",")",a,b)};T.prototype.l=!0;T.prototype.g=function(b,a){return Z.call(j,$,"("," ",")",a,b)};Nb["boolean"]=!0;
Pb["boolean"]=function(b){return F.call(j,Q.call(j,b))};Nb.string=!0;Pb.string=function(b,a){return z(mc.call(j,b))?F.call(j,Q.call(j,":",function(){var a=qd.call(j,b);return z(a)?Q.call(j,a,"/"):j}(),pd.call(j,b))):z(nc.call(j,b))?F.call(j,Q.call(j,function(){var a=qd.call(j,b);return z(a)?Q.call(j,a,"/"):j}(),pd.call(j,b))):z("\ufdd0'else")?F.call(j,z("\ufdd0'readably".call(j,a))?ha.call(j,b):b):j};W.prototype.l=!0;W.prototype.g=function(b,a){return Z.call(j,$,"["," ","]",a,b)};Fc.prototype.l=!0;
Fc.prototype.g=function(b,a){return Z.call(j,$,"("," ",")",a,b)};Nb.array=!0;Pb.array=function(b,a){return Z.call(j,$,"#<Array [",", ","]>",a,b)};Gc.prototype.l=!0;Gc.prototype.g=function(){return F.call(j,"()")};Jc.prototype.l=!0;Jc.prototype.g=function(b,a){return Z.call(j,$,"("," ",")",a,b)};X.prototype.l=!0;X.prototype.g=function(b,a){return Z.call(j,function(b){return Z.call(j,$,""," ","",a,b)},"{",", ","}",a,b)};function vd(b){alert.call(j,b);return j}function wd(){return cd.call(j,function(b){return Rc.call(j,0,b)},V.call(j,function(b){return rc.call(j,1,b)},lb.call(j,"coins").value.split(" ")))}function xd(){return rc.call(j,1,lb.call(j,"target").value)}function yd(b){return lb.call(j,"results").innerHTML=ud.call(j,b)}hb.call(j,lb.call(j,"do-calculation"),"click",function(){return yd.call(j,zd.call(j,wd.call(j),xd.call(j)))});
function Ad(b,a){return Qc.call(j,wc,cd.call(j,function(b){return uc.call(j,a,b)},b))}var zd=function(){function b(a,b,f){for(;;){var g=Ad.call(j,a,b);if(z(Yb.call(j,g)))return vd.call(j,"No solution");else if(z(D.call(j,g,b)))return S.call(j,g,f);else if(z(P.call(j,g,b)))b=qc.call(j,b,g),f=S.call(j,g,f);else return j}}var a=j;return a=function(d,e,f){switch(arguments.length){case 2:return Ic.call(j,a.call(j,d,e,F.call(j)));case 3:return b.call(this,d,e,f)}c("Invalid arity: "+arguments.length)}}();